### ISSUE TITLE
Import/Export mit ili2db-3.x-Schemen

### ISSUE THREAD

**Issue by schmandr** [sogis/gretl#10]
GRETL latest nutzt ili2pg v4.0.0. Dadurch funktioniert _ili2pgExport_ und _ili2pgImport_ nicht mit Schemen, die mit ili2pg v3.x angelegt worden sind. Für den Export gäbe es ab ili2pg v4.1.0 die Option `--export3`, damit das trotzdem ginge. Der _ili2pgExport_ müsste hierfür erweitert werden. Aber was ist mit dem Import (und mit _ili2pgReplace_, _ili2pgUpdate_)?

Müssen wir uns auch etwas für _ili2pgImportSchema_ überlegen? Vielleicht nicht, weil wir das in der GDI nicht verwenden.

**Comment by claeis** [comment]
Import mit 4.x in ein 3.x Schema geht absichtlich nicht. Man soll die DB-Schemas migrieren.

**Comment by schmandr** [comment]
Genau. Wir lösen dies nun durch Migration der DB-Schemen nach Version 4.x. Weil sich dies über einen längeren Zeitraum erstreckt, haben wir im _GRETL-Jenkins_ noch einen zweiten Jenkins Agent definiert, der ili2pg 4.x anbietet.
