### ISSUE TITLE
Request auf /pubsignal bleibt aus, obwohl request auf /doc abgesetzt wird

### ISSUE THREAD

**Issue by ojeker** [sogis/gretl#100]
Fehler im Log:

    failed to run Publisher
    java.io.IOException: failed to send get doc request to service at http://simi.gdi-production.svc/app/rest

Volles log: [pubsignal.log](https://github.com/sogis/gretl/files/10285645/pubsignal.log)

Der Fehler ist jedoch "nur" ein Folgefehler: /doc schlägt fehl, da das Datenblatt ohne vorherige publikation auf /pubsignal nicht erzeugt werden kann.

Aus dem log von SIMI (Serverseitig) wird klar, dass der Aufruf /pubsignal nicht ankommt. Beim Simulieren des Publisher mittels CURL funktioniert es.

Publisher-Konf:
    
    task publipub(type: Publisher, dependsOn:'writeToPub'){
      dataIdent = "ch.so.afu.abbaustellen"
      userFormats = true
      database = [dbUriPub,dbUserPub,dbPwdPub]
      dbSchema = "afu_abbaustellen_pub_v2"
      modelsToPublish = "SO_AFU_ABBAUSTELLEN_Publikation_20221103"
    
      target = ["sftp://$sftpServerSogis/$sftpUserSogis", sftpUserSogis, sftpPwdSogis]
      kgdiService = [simiMetadataServiceUrl, simiMetadataServiceUser, simiMetadataServicePwd]
      kgdiTokenService = [simiTokenServiceUrl, simiTokenServiceUser, simiTokenServicePwd]
      grooming = new File(file(projectDir).getParentFile(), "publisher_grooming.json")
      if (findProperty('ilivalidatorModeldir')) modeldir = ilivalidatorModeldir
    }

**Comment by claeis** [comment]
Was steht im Log?

**Comment by claeis** [comment]
Aha:

> Der Fehler ist jedoch "nur" ein Folgefehler: /doc schlägt fehl, da das Datenblatt ohne vorherige publikation auf /pubsignal nicht erzeugt werden kann.

Der aktuelle Code macht (aus der Ueberlegung: ohne Doku ist die Publikation unvollständig):
  
1. getLeaflet() "/doc"
2. notifyPublication() "/pubsignal"

**Comment by ojeker** [comment]
Ah - Verstehe den Hintergrund.

Kannst du die Reihenfolge umdrehen? Der Publisher wird wie gewünscht auch fehl schlagen, falls /doc als zweites aufgerufen wird. Damit is t klar, dass die Publikation nicht erfolgreich war...

**Comment by claeis** [comment]
Ja, kann ich umdrehen. (Aber in den KGDI-Metadaten hat man dann evtl. den Eindruck, die Publikation war erfolgreich...obwohl sie es nicht war)

**Comment by ojeker** [comment]
Super - Danke. Und Korrekt bezüglich der Metadaten - fällt trotzdem "genügend" auf, da der Job fehlschlägt.
