### ISSUE TITLE
Grooming schlägt bei neuen Themen ohne /hist Ordner fehl

### ISSUE THREAD

**Issue by ojeker** [sogis/gretl#101]
Publisher bricht mit Fehlermeldung ab, sobald er zum grooming kommt.

Ausschnitt aus log:

    failed to run Publisher
    java.nio.file.NoSuchFileException: /gretl/ch.so.afu.geologie/hist: No such file

Volles log: [grooming.log](https://github.com/sogis/gretl/files/10285558/grooming.log)

Grooming-Konfiguration:

    {
      "grooming": {
        "daily": {
           "from": 2,
           "to": 7
        },
        "weekly": {
           "from": 7,
           "to": 31
        },
        "monthly": {
           "from": 31,
           "to": 303
        },
        "yearly": {
           "from": 303,
           "to": null
        }
      }
    }

Publisher-Konfiguration:

    task publishPub(type: Publisher, dependsOn: 'transferAfuGeologiePub'){
        database = [dbUriPub, dbUserPub, dbPwdPub]
        dataIdent = "ch.so.afu.geologie"
        dbSchema = "afu_geologie_pub_v1"
        modelsToPublish = "SO_AFU_Geologie_20200831"
        userFormats = true
        target = ["sftp://$sftpServerSogis/$sftpUserSogis", sftpUserSogis, sftpPwdSogis]
        kgdiService = [simiMetadataServiceUrl, simiMetadataServiceUser, simiMetadataServicePwd]
        kgdiTokenService = [simiTokenServiceUrl, simiTokenServiceUser, simiTokenServicePwd]
        grooming = new File(file(projectDir).getParentFile(), "publisher_grooming.json")
        if (findProperty('ilivalidatorModeldir')) modeldir = ilivalidatorModeldir
    }

**Comment by claeis** [comment]
- Was genau schlägt fehl? 
- Was passiert, was passiert nicht?
- Was steht im Log?
