### ISSUE TITLE
[Publisher]: Fehler bei Stream-Eröffnung auf *.zip auf SFTP

### ISSUE THREAD

**Issue by ojeker** [sogis/gretl#104]
Seit der Ausführung am 22. Februar 00:15 Uhr bricht der neue AV-Job jede 2. bis 3. Nacht mit Fehler ab.

Fehlermeldungen:

22.02.2023

    failed to run Publisher
    java.nio.file.NoSuchFileException: /gretl/.2023-02-22/2425.ch.so.agi.av.mopublic.xtf.zip: No such file

24.02.2023

    failed to run Publisher
    java.nio.file.NoSuchFileException: /gretl/.2023-02-24/2465.ch.so.agi.av.mopublic.gpkg.zip: No such file

Ausgelöst durch Codezeilen mit Inhalt:

    out = new ZipOutputStream(Files.newOutputStream(targetFile));

Aufgefallen ist mir - Kann aber keinen direkten Bezug zum Fehler herstellen:
- Der Fehler tritt bis jetzt ausschliesslich bei Modell MOpublic auf (Export mit Quelle = Db)
- Geschrieben wird in ein verstecktes Datums-Verzeichnis direkt im Root des SFTP-Benutzers "gretl". Beispiel: /gretl/.2023-02-25/2572.ch.so.agi.av.mopublic.gpkg.zip. Wie erfolgt so die Abgrenzung zu weiteren parallel laufenden Publikationen von anderen Themen?
- Tritt eher auf, wenn viele Gemeinden zu verarbeiten sind.
- Tritt unabhängig vom Inhalt des *.zip auf (Beim Schreiben von *.mopublic.gpkg.zip und *.mopublic.xtf.zip)

Beachten bezüglich Zeilennummern im Stacktrace: Die Logs entsprechen der GRETL-Version unmittelbar nach Commit [872d44b](https://github.com/sogis/gretl/commit/872d44b3b1118d1aacdeb541a670b5da8166aab8) on Dec 22.

Log-Dateien im Anhang:
* [run19_20230225.txt](https://github.com/sogis/gretl/files/10838392/run19_20230225.txt)
* [run17_20230224.txt](https://github.com/sogis/gretl/files/10838394/run17_20230224.txt)
* [run15_20230222.txt](https://github.com/sogis/gretl/files/10838396/run15_20230222.txt)

Betroffener Job: https://github.com/sogis/gretljobs/tree/main/agi_av_dm01_mopublic_pub

**Comment by edigonzales** [comment]
Ist https://gretl-i.so.ch/job/awjf_wald_pub/31/console ein anderes Problem? Da wurde das Datenblatt  nicht gefunden. Auch mit einer NoSuchFileException:

```
failed to run Publisher
java.nio.file.NoSuchFileException: /gretl-test/.2023-02-23/meta/datenbeschreibung.html: No such file
	at com.github.robtimus.filesystems.sftp.DefaultFileSystemExceptionFactory.asFileSystemException(DefaultFileSystemExceptionFactory.java:126)
	at com.github.robtimus.filesystems.sftp.DefaultFileSystemExceptionFactory.createNewOutputStreamException(DefaultFileSystemExceptionFactory.java:89)
	at com.github.robtimus.filesystems.sftp.SSHChannelPool$Channel.newOutputStream(SSHChannelPool.java:423)
	at com.github.robtimus.filesystems.sftp.SFTPFileSystem.newOutputStream(SFTPFileSystem.java:280)
	at com.github.robtimus.filesystems.sftp.SFTPFileSystem.newOutputStream(SFTPFileSystem.java:253)
	at com.github.robtimus.filesystems.sftp.SFTPPath.newOutputStream(SFTPPath.java:163)
	at com.github.robtimus.filesystems.sftp.SFTPFileSystemProvider.newOutputStream(SFTPFileSystemProvider.java:232)
	at ch.so.agi.gretl.steps.PublisherStep.publishFilePost(PublisherStep.java:671)
	at ch.so.agi.gretl.steps.PublisherStep.publishDatasetFromDb(PublisherStep.java:241)
	at ch.so.agi.gretl.tasks.Publisher.publishAll(Publisher.java:203)

```

**Comment by edigonzales** [comment]
@ojeker 
> Geschrieben wird in ein verstecktes Datums-Verzeichnis direkt im Root des SFTP-Benutzers "gretl". Beispiel: /gretl/.2023-02-25/2572.ch.so.agi.av.mopublic.gpkg.zip. Wie erfolgt so die Abgrenzung zu weiteren parallel laufenden Publikationen von anderen Themen?

Ist das ein Verzeichnis auf denm SFTP-Server?

**Comment by edigonzales** [comment]
Mmmh, kann man die "robtimus" oder der darunterliegenden "jsch" library irgendwie beibringen mehr zu loggen? Vielleicht sind das Verbindungsprobleme zwischen Pod/Cluster und dem SFTP-Server? 

Macht der Publisher-Task immer eine neue FTP-Verbindung beim Schreiben einer Bibliothek? Vielleicht gibt es zu viele Verbindungen?

**Comment by claeis** [comment]
Also ich vermute mal, verschiedene Jobs schreiben ins selbe temporäre Verzeichnis im Ziel. Und einer von den Jobs ist dann fertig, löscht dieses temporäre Verzeichnis, und dann finden es die anderen Jobs nicht mehr...

Vorschlag: statt ${target}/.${date} neu ${target}/.${uuid}

**Comment by ojeker** [comment]
> Also ich vermute mal, verschiedene Jobs schreiben ins selbe temporäre Verzeichnis im Ziel. Und einer von den Jobs ist dann fertig, löscht dieses temporäre Verzeichnis, und dann finden es die anderen Jobs nicht mehr...
> 
> Vorschlag: statt target/.{date} neu target/.{uuid}

Alternative: .{date} innerhalb des Verzeichnisses der Themenbereitstellung erstellen - also target/{bereitstellung}/.{date}.  Wäre transparenter. Beispiel für Bereitstellungsordner ch.so.afu.geologie: https://files.geo.so.ch/ch.so.afu.geologie/ 

In jedem Fall muss erhalten bleiben, dass bei Ausführungen am gleichen Tag die Historisierung nicht angestossen wird.
