### ISSUE TITLE
Publisher: Grooming der Archivstände findet nicht statt

### ISSUE THREAD

**Issue by ojeker** [sogis/gretl#105]
Das Grooming ist für alle Publisher aller Themen einheitlich hier definiert: https://github.com/sogis/gretljobs/blob/main/publisher_grooming.json

Nach meinem Verständnis sollte mit dieser Konfiguration für historisierte Stände bei einem Alter zwischen 7 und 31 Tagen (also grob "> 1 Woche" und "< ein Monat" pro Woche ein "Wochenstand" (= weekly) erhalten bleiben. 

Es scheinen aber alle Stände erhalten zu bleiben. Verständnis falsch? Konfigurationsfehler? Greift das Grooming nicht?

Konfiguration und Inhalt des Ordner /hist am Beispiel der Forstreviere:
* https://github.com/sogis/gretljobs/blob/main/awjf_forstreviere_pub/build.gradle
* https://files.geo.so.ch/ch.so.awjf.forstreviere/hist/

Log des Jobs: [forstreviere.txt](https://github.com/sogis/gretl/files/10840636/forstreviere.txt)

**Comment by claeis** [comment]
Ich sehe in dem Log kein Einträge vom Publisher!?  (wie z.B. von ```log.info("Reading grooming conf: " + groomingJson);```)

**Comment by ojeker** [comment]
Ich habe unter https://github.com/sogis/publisher_test im Verzeichnis "groomjob" ein Abbild unserer Konfiguration erstellt. 
Logs mit level info und debug liegen bei.

Mein Verständnis/Erwartung ist, dass bei Ausführung des jobs (publisher_test/groom_run.sh) entweder der historisierte Stand 2023-02-19 oder 2023-02-20 gelöscht wird - passiert aber nicht. 2023-02-27 wird neu als historisierter Stand angelegt.

[log_debug.txt](https://github.com/sogis/gretl/files/10850262/log_debug.txt)
[log_info.txt](https://github.com/sogis/gretl/files/10850269/log_info.txt)

**Comment by ojeker** [comment]
@claeis Ich habe ein Beispiel isoliert (Siehe letzter Kommentar). Kannst du dich melden, falls du weiteres zum Nachvollzug brauchst? Wir müssen das Issue gelöst bekommen - die Archivstände sammeln sich an...

**Comment by claeis** [comment]
In welcher Einheit sind die Zahlen im json? Immer/Bei allen Abschnitten (daily, weekly, monthly, yearly) in  Tagen?

**Comment by ojeker** [comment]
> In welcher Einheit sind die Zahlen im json? Immer/Bei allen Abschnitten (daily, weekly, monthly, yearly) in Tagen?

Ja - Ist gut, wenn das in der Doku dann auch noch vorkommt...

Im Beispiel https://github.com/sogis/publisher_test/blob/main/publisher_grooming.json bedeutet

        "daily": {
           "from": 0,
           "to": 7
        },

, dass vom aktuellen Stand sieben Tage zurück alle vorhandenen Tagesstände beibehalten werden. Der Stand acht Tage zurück fällt im Beispiel dann unter "weekly". Falls es in "seiner" Woche mehrere Stände gibt -> ausdünnen auf einen Stand.
