### ISSUE TITLE
CsvImport Failed 

### ISSUE THREAD

**Issue by EchoCharlie85** [sogis/gretl#11]
In einem Gretl-Job verwende ich den Task CsvImport. 

```
task csvimport(type: CsvImport, dependsOn: unpackFiles){
    database = [dbUriEdit, dbUserEdit, dbPwdEdit]
    schemaName = "alw_infoflora"
    tableName = "neophyten_neophytenstandorte"
    firstLineIsHeader=true
    valueSeparator = ";"
    dataFile = file(pathToUnzipFolder.toString()+'/neophyten_neu.csv')
}
```
Dieser sollte die Daten aus "neophyten_neu.csv" (Diesem Ticket angehängt mit txt am Ende, da Git keine Csv-Files akzeptiert) ins Schema alw_infoflora importieren (ili-File im Anhang). 

Die Fehlermeldung die dabei erscheint, besagt: 

> Caused by: org.postgresql.util.PSQLException: FEHLER: NULL-Wert in Spalte ?v_doupt_status? verletzt Not-Null-Constraint
  Detail: Fehlgeschlagene Zeile enth?lt (4, a61e9e0d-04cc-4105-b124-6a684fdf620c, 136, 65250, Info Flora (Archiv Atlas Welten & Sutter), 2595500.04080586, 1227299.94680526, 500, Daelen, null, 1038140, Reynoutria japonica Houtt., Japanischer Staudenknoeterich, Schwarze Liste, null, null, null, 1992-09-20, 681, Vorhanden, 921, Einzelfundmeldung, null, null, null, null, null, null, null, null, null, null, 829, Feldbeobachtung, 666, Trallallii, 888, Trallalloooo, null, null, Mueller-Wirz Ernstlilili, SO, null, null).

Die beiden Werte vor "Mueller-Wirz Ernstlilili" sind im CSV nicht NULL, werden vom CsvImport-Task aber - aus unerfindlichen Gründen -  als NULL interpretiert, was dann zum oben stehenden Fehler führt. Frage: Wieso werden diese beiden Werte als NULL interpretiert?  

[SO_ALW_Infoflora_20190523.ili.txt](https://github.com/sogis/gretl/files/3224267/SO_ALW_Infoflora_20190523.ili.txt)

[neophyten_neu.csv.txt](https://github.com/sogis/gretl/files/3223994/neophyten_neu.csv.txt)

**Comment by edigonzales** [comment]
Was passiert, wenn `v_doupt_status ` nicht `BOOLEAN` ist, sondern z.B. `TEXT`?

**Comment by edigonzales** [comment]
Bemerkung zum Modell: Ob man die Koordinate eines Neophytec auf die circa Trillionste Stelle genau bestimmen muss, bleibt fraglich.

**Comment by EchoCharlie85** [comment]
Wenn v_doupt_status in der Tabelle selbst geändert wird (zu z.B. Varchar) ist der Fehler genau gleich. Im Modell selbst habe ich den Datentyp allerdings noch nicht geändert. 

Zum Modell: Ja, das ist tatsächlich fraglich. Aber da die Koordinaten mit Nachkommastellen geliefert werden, muss ich sie auch so importieren. Wenn ich bei den Koordinaten als Datentyp Integer habe, fällt der CSV-Import schon dort durch.

**Comment by edigonzales** [comment]
Muss ja nicht Integer sein, würde ja schon reichen, wenn man auf Dezimeter rundet.

**Comment by EchoCharlie85** [comment]
Auf jeden Fall. Nur: Ich kann erst runden, wenn das CSV importiert ist. Aber eben: Es wird nicht importiert.

**Comment by schmandr** [comment]
Das Modell ist einfach fehlerhaft:

- Attribut `v_doupt_status` heisst im CSV `v_doubt_status`
- Attribut `v_doupt_status_descript` heisst im CSV `v_doubt_status_descript`
- Und Attribut `code_unit_description` heisst im CSV `count_unit_descript`

**Comment by EchoCharlie85** [comment]
@schmandr : Ja, das stimmt. Aber es ist nicht das einzige Problem. Auch nach den Korrekturen macht der CSV-Importer Probleme. 

Grund 1: Die Spaltennamen des CSV und der Tabelle werden gemappt. Dass nicht alle Tabellen-Spalten mit CSV-Daten befüllt werden müssen, ist gut und korrekt. Wenn aber im CSV Spalten vorhanden sind, die auf keine Spalte in der Tabelle passen, dann sollte meines Erachtens eine Fehlermeldung erscheinen. 

Grund 2: Die Daten im CSV müssen nicht zwangsläufig in Anführungszeichen (") stehen. Das ist soweit gut und OK. Wenn aber ein Feld leer ist, dann fällt der CSV-Import durch.

Leeres Feld ;; = Falsch. 
Leeres Feld ;""; = Richtig.

Meines Erachtens sind das zwei Bugs oder zumindest "Unschönheiten" im CSV-Import-Task.
