### ISSUE TITLE
Publisher erstellt einen Unterordner "build", löscht ihn aber nicht mehr

### ISSUE THREAD

**Issue by schmandr** [sogis/gretl#118]
Wahrscheinlich hier
https://github.com/sogis/gretl/blob/7b57cc11784ed6344c6826037898d550f7071178/gretl/src/main/java/ch/so/agi/gretl/tasks/Publisher.java#L197
erstellt Publisher einen Unterordner "build", den wohl er als temporäres Verzeichnis benötigt. Aber er löscht den Ordner am Ende nicht mehr.

**Comment by ojeker** [comment]
Handelt es sich um das Default-Build Verzeichnis von Gradle (/build)? In /build werden von verschiedenen Tasktypen Artefakte abgelegt. Kann und soll ein einzelner Task ein Job-Globales Verzeichnis löschen?

**Comment by schmandr** [comment]
Ja, das ist das Default-Build-Verzeichnis von Gradle. Dieses soll besser nicht gelöscht werden. Oder idealerweise erst nach Abschluss des Jobs.

Aber lassen wir es bleiben, so schlimm ist die Sache ja nicht.
