### ISSUE TITLE
Doku Curl-Task prüfen

### ISSUE THREAD

**Issue by schmandr** [sogis/gretl#119]
Stimmen in den Beispielen für die Verwendung des _Curl_-Tasks die folgenden Zeilen?
https://github.com/sogis/gretl/blob/8ed25474df88f1eaff1077bbddd634dff76a1ec3/docs/user/index.md?plain=1#L382
https://github.com/sogis/gretl/blob/8ed25474df88f1eaff1077bbddd634dff76a1ec3/docs/user/index.md?plain=1#L394
https://github.com/sogis/gretl/blob/8ed25474df88f1eaff1077bbddd634dff76a1ec3/docs/user/index.md?plain=1#L406

Das hat bei mir nicht funktioniert, sondern ich musste
```
method = 'GET'
```
setzen.

**Comment by edigonzales** [comment]
"Eigentlich" schon: https://github.com/sogis/gretl/blob/master/gretl/src/integrationTest/jobs/CurlDownload/build.gradle

Job wird beim Testen ausgeführt. Komisch, komisch...

**Comment by edigonzales** [comment]
@schmandr Ah, hast du MethodType importiert? Falls nein, greift eventuell Gradle-Magic. Falls dem so ist, müsste ich das dokumentieren.

**Comment by schmandr** [comment]
Nein, hab' ich nicht importiert. Ja, mit dem `import` gehts. Und ohne `import` passiert wohl wirklich irgendeine Magic.

**Comment by edigonzales** [comment]
fixed https://github.com/sogis/gretl/commit/81b1b24e5337b954a013354db8265a1b319a86a3
