### ISSUE TITLE
Überbleibsel aus früheren Zeiten

### ISSUE THREAD

**Issue by schmandr** [sogis/gretl#12]
Diese Zeile muss wohl nicht mehr so lauten:
https://github.com/sogis/gretl/blob/bcac81d72ed93b05efd43645108ba9b58deb6334/Jenkinsfile#L14

**Comment by edigonzales** [comment]
fixed https://github.com/sogis/gretl/commit/2f714ef401b60c377bfd471dc60bdd70cd8d6a54
