### ISSUE TITLE
Fehler bei Ili2pgReplace mit Tag 2.3.420

### ISSUE THREAD

**Issue by schmandr** [sogis/gretl#123]
Mit Tag 2.3.420 kriege ich bei _Ili2pgReplace_ folgende Fehlermeldung. Mit Tag 2.3.418 tritt das Problem nicht auf.

```
Execution failed for task ':importDataset_2425'.
> org.gradle.api.internal.file.DefaultFilePropertyFactory$DefaultDirectoryVar$3 cannot be cast to java.util.ArrayList
```
Der Task sieht so aus:

```
    task "importDataset_$dataSetName"(type: Ili2pgReplace) {
        group = 'Copy datasets'
        description = 'Import dataset'
        dependsOn "exportDataset_$dataSetName"
        doLast {
            println "Dataset ${dataSetName} imported into DB schema ${schemaName}"
        }
        database = [dbUriEdit, dbUserEdit, dbPwdEdit]
        dbschema = schemaName
        models = modelNames
        dataFile = layout.buildDirectory.file(fileName)
        dataset = dataSetName
        disableRounding = true
        disableValidation = true
        //finalizedBy "removeFiles_$dataSetName"
    }
```

Das `layout.buildDriectory.file(fileName)` mache ich, weil ich die Dateien ins _build_-Directory statt ins _Temp_ platzieren und von dort lesen möchte, damit ich sie mir bei Bedarf anschauen kann. Die Schreibweise wird von Gradle so irgendwo empfohlen.

**Comment by edigonzales** [comment]
@schmandr Hast du noch mehr von der Fehlermeldung?

**Comment by edigonzales** [comment]
@schmandr Kannst du mal mit `layout.buildDirectory.file(fileName).get()` probieren. Eigentlich ist der Rückgabewert von file(fileName) ein "Provider<RegularFile>". Ad hoc dürfte das nicht gehen. Aber bei der Magie weiss man ja nie, v.a. wenn du sagst mit einer älteren Version geht es.

**Comment by schmandr** [comment]
@edigonzales mit `....get()` hat es auch nicht funktioniert. (Gleiche Fehlermeldung.)

Es gibt leider auch mit `--debug` nicht mehr von der Fehlermeldung.

Interessant: Zuerst mach ich einen _Ili2pgExport_, ebenfalls mit `dataFile = layout.buildDirectory.file(fileName)`, und das funktioniert problemlos. Vielleicht hilft dir das für _Ili2pgReplace_?

**Comment by schmandr** [comment]
Meldungen mit `-s`:

```
Caused by: java.lang.ClassCastException: org.gradle.api.internal.file.DefaultFilePropertyFactory$DefaultDirectoryVar$3 cannot be cast to java.util.ArrayList
	at ch.so.agi.gretl.tasks.Ili2pgReplace.replaceData(Ili2pgReplace.java:59)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)

```

**Comment by edigonzales** [comment]
@schmandr Also, wenn man einfach `file("gaga.xtf")` verwendet, funktioniert es. Das Objekt ist im Task ein `java.io.File`. Wenn man nun aber Super-Magie à la `layout.buildDirectory.file("gaga.xtf")` verwendet, funktioniert es nicht. Das Objekt ist `org.gradle.api.internal.file.DefaultFilePropertyFactory$DefaultDirectoryVar$3`.

**Comment by edigonzales** [comment]
@schmandr Ich tendiere zu "won't fix". Das mit dieser Property-API ist mir nicht ganz klar: Was muss auf Task-Seite bei den Parametern gemacht werden, damit das richtig funktioniert (und nicht bloss zufällig)?

Was z.B. geht `dataFile = file(layout.getBuildDirectory().file('Beispiel2a.xtf').get())`

Weil ich explizit dieses "dataFile instanceof XXXX" mache, greift vielleicht ein gewisser Automatismus nicht mehr. Aber dass das vorher ging, war wohl eher Zufall. Der Task ist sicher nicht bewusst auf die Property-API ausgelegt.
