### ISSUE TITLE
Parameter createEnumTabsWithId fehlt in Ili2pgImportSchema task

### ISSUE THREAD

**Issue by webrian** [sogis/gretl#124]
Der ili2db Parameter *createEnumTabsWithId* fehlt im Ili2pgImportSchema task, somit kann dieser in einem Schema Job nicht verwendet werden.

Dies entgegen der Schema Job Dokumentation: https://github.com/sogis/schema-jobs/tree/main#datei-schemaproperties

Fehlermeldung bei ausführen eines Schema Jobs mit *createEnumTabsWithId*:

```
* Where:
Build file '/home/gradle/schema-jobs/shared/schema/build.gradle' line: 161

* What went wrong:
A problem occurred evaluating root project 'schema-tasks-shared'.
> Could not set unknown property 'createEnumTabsWithId' for task ':createSchemaShared' of type ch.so.agi.gretl.tasks.Ili2pgImportSchema.
```

@schmandr

**Comment by schmandr** [comment]
Hoppla. Diese Option ist bei den Schema-Jobs (wie dokumentiert) zwar verfügbar: https://github.com/sogis/schema-jobs/blob/d8bdb96a29a5ab452ec7b61065f4e7914fbf6425/shared/schema/build.gradle#L160.

Allerdings ist sie in GRETL gar nicht exposed, weshalb ein Schema-Job sie gar nicht verwenden kann: https://github.com/search?q=repo%3Asogis%2Fgretl+createEnumTabs&type=code

Dann musst du im [gretl](https://github.com/sogis/gretl)-Repository ein Ticket für @edigonzales machen.

**Comment by webrian** [comment]
@edigonzales Darf ich dich bitten, diesen Parameter im Ili2pgImportSchema noch zu ergänzen?

**Comment by edigonzales** [comment]
fixed https://github.com/sogis/gretl/commit/047efb7cf5b5d5a03108172e72e404a7d160c03e
