### ISSUE TITLE
Gradle Update

### ISSUE THREAD

**Issue by Saela** [sogis/gretl#125]
Currently used Version: 5.1.1 (https://github.com/sogis/gretl/blob/master/gradle/wrapper/gradle-wrapper.properties)

Target Version: Newest (currently: v8.5) => https://gradle.org/releases/

Linked issues:

- #126 
- #127 
- #128

**Comment by edigonzales** [comment]
Es könnte sein, dass es Getter/Setter braucht ab bestimmten Gradle-Versionen und nicht nur ein public Field.

**Comment by Saela** [comment]
> Es könnte sein, dass es Getter/Setter braucht ab bestimmten Gradle-Versionen und nicht nur ein public Field.

Danke für die Info!
