### ISSUE TITLE
Re-Organize build.gradle files

### ISSUE THREAD

**Issue by Saela** [sogis/gretl#130]
The work that needs to be done here still has to be discussed in detail. There's a couple of things we could do like e.g. use buildsrc or a root-gradle file.

What to do:

1. Check if the business logic is clear and easily understandable as requested by @edigonzales in the comment below.
2. Discuss if some improvements came up and decide on measures to be taken.

The first step should be done as a timebox of 4h.

**Comment by edigonzales** [comment]
Es gibt 3 build.gradle und 1 integration-test.gradle Datei. Diese beinhalten die build-Businesslogik. dependencies.gradle, settings.gradle und versioning.gradle zähle ich nicht dazu.

Mich würde interessieren, ob die Aufteilung der Businesslogik nachvollziehbar ist. Ist es halbwegs transparent was abgeht? Oder sucht man sich den Wolf in den verschiedenen Files, wenn man verstehen will wie etwas geht.

**Comment by Saela** [comment]
@edigonzales Grundsätzlich finde ich ist es klar mit der aktuellen Konfiguration. Gut finde ich auch, dass die Integration Test Konfiguration in einem separaten gradle file ist. Das macht es etwas übersichtlicher, da mehr als ein Integrationtest verwendet wird. Von meiner Seite her passt das.

Seit Gradle 6 gibt es aber die Best Practice nicht mehr ein Root Gradle File zu führen (gretl/gradle.build) sondern in Multi Project Builds mit einem buildSrc Projekt zu arbeiten. Siehe auch die Dokumentation für Gradle 8.7: https://docs.gradle.org/current/userguide/organizing_gradle_projects.html#sec:build_sources

Ist das ok, wenn ich das an die aktuellen Best Practices anpassen und ein buildSrc Projekt/Folder erstellen würde?

**Comment by Saela** [comment]
@edigonzales Ist das ok, wenn ich anstelle des Root Gradle Files die aktuelle Best Practice mit buildSrc Ordner implementiere? Siehe auch Gradle 8.7 Docs: https://docs.gradle.org/current/userguide/organizing_gradle_projects.html#sec:build_sources

**Comment by edigonzales** [comment]
@Saela Ich verstehe die Best Practice nicht ganz. Wenn ich z.B. eine Java-Anwendung programmiere und für diese ein Gradle-Plugin benötige, würde man den Plugin-Code in buildSrc verwalten. Unsere Java-Anwendung ist jedoch das Plugin selber, was käme dann in buildSrc?

**Comment by Saela** [comment]
@edigonzales Ich habe mich nochmals schlau gemacht. In den Best Practices wie ein Gradle Projekt aufgebaut werden soll, habe ich nirgends mehr ein root build.gradle file gefunden und auch keine Erwähnung davon. In der Dokumentation für Version 5 steht es noch explizit drin. Offenbar ging das vergessen, oder ist nicht mehr Pflicht. Ich konnte es nicht rausfinden.

Zudem habe ich mir nochmals die buildSrc Definition angeschaut und gebe dir Recht, es ist nicht das was wir hier brauchen. Unsere Situation ist ja etwas anders als bei einem "Standard" Projekt mit Gradle. :) 

Ich würde das Ticket dann schliessen? Ist das ok?

**Comment by Saela** [comment]
@edigonzales Ich denke, das Ticket hier kann geschlossen werden. Siehe auch mein Kommentar oben. Oder siehst du das anders?

**Comment by edigonzales** [comment]
Ok.
