### ISSUE TITLE
Switch to versioning catalog

### ISSUE THREAD

**Issue by Saela** [sogis/gretl#131]
This depends on the gradle update as version catalogs are only available since gradle 7.4. If we have the correct gradle min version we can just rename the existing `dependencies.gradle` file to `libs.versions.toml`.

Also check dependencies directly managed in build.gradle files that are not in the dependencies.gradle file and move them to the versioning catalog.

**Comment by edigonzales** [comment]
z.K. es gibt einige Dependencies, die direkt build.gradle verwaltet werden (und nicht im dependencies.gradle). Diese müsste man auch in den versioning catalog zügeln.
