### ISSUE TITLE
Switch to Property Api / Lazy Configuration

### ISSUE THREAD

**Issue by Saela** [sogis/gretl#132]
There's a comment in the github issues that this was already done once and resulted in a lot of errors. This could be because gradle now differs between read-only and readable/writeable properties. 

That's still something that has to be discussed and properly specified. But it will generate a lot of changes because every task has to be changed.

**Comment by edigonzales** [comment]
Ja, hier ist erstmals Fleisch am Knochen...

Kontext (und so wie ich es verstanden habe): Ohne Verwendung der Property-API ist keine Lazy Configuration möglich. D.h. dass Gradle zur Configuration Phase (https://docs.gradle.org/current/userguide/build_lifecycle.html) alles wissen muss. Vor allem muss es die Werte der Task-Properties kennen. Also z.B. den Namen der Datei, die man im Validator-Task prüfen will. 

Pseudecode:
```
def fileName = null;
task foo () {
  doLast {
   fileName = "hallo.xtf"
  }
}

task validate(type: 'ilivalidator') {
   dataFile = fileName
}
```

Funktioniert nicht, weil dataFile null wird sein. Wenn dataFile nun so ein Property-Teil ist, würde es gehen. Wie gesagt: Mein Kenntnisstand. 

Alles umschreiben auf Property-API ist natürlich mit Impacts verbunden:
- Aufwand
- Mir wäre auch nicht ganz klar, was die "richtige" Syntax ist. Es gibt den Ansatz mit alles "abstract" und die Properties auch gleich zu Managed Properties zu machen. Schon diese Abgrenzung ist mir nicht mehr ganz klar.
- Mir war auch nicht klar, wie ich gewisse Abkürzungen machen kann, die aus Aussensicht für GRETL-Job-Autor praktisch sind: Z.B. gibt es die eigene Connector-Klasse. Für den Autor sieht das wie eine Liste aus: `[dburl, dbusr, dbpwd]`. War nicht fähig das auf die Property-API umzuschreiben ohne Eleganz-Verlust.
- Beim Feldversuch hatte ich auch das von dir erwähnte Problem mit den Warnungen/Fehlermeldungen. Ich _glaube_ es war z.B. wenn mehrere Tasks in den gleichen Ordner schreiben oder so. Da erwartet Gradle, dass man das sauber/anders löst. Könnte aber auch "nur" eine Gradle-Versionsproblematik sein. 

Sowohl Code und wirrer Text zu den Problemen hier: https://github.com/edigonzales/gretl-ng Insbesondere ab Textstelle "Für die eigenen Tasks..." inkl. Fehlermeldungen, die man Googeln kann. 

Langer Rede, kurzer Sinn: Ich wäre froh, wenn du/ihr hier ein wenig Wissen erarbeiten könntet. Was ist was? Was führt zu welchen Problemen? Dann Entscheid, ob man auf diesen Zug auspringen will. Oder nur bei Bedarf (an einer einzigen Stelle vewenden wir bereits lazy configuration).

**Comment by Saela** [comment]
@edigonzales Ich habe mich etwas vertiefter mit der Lazy Configuration von Tasks auseinander gesetzt. Grundsätzlich empfiehlt Gradle, Lazy Configuration zu verwenden, da sich die Build Zeit optimieren lässt. In der Doku findet man aber bei den Custom Tasks auch Beispiele ohne Property/Provider Api. 

In den meisten Blogs, speziell auch für eigene Gradle Plugins, wird ebenfalls darauf hingewiesen, dass sich Lazy Configuration lohnt und empfohlen wird. Z.B. hier: https://melix.github.io/blog/2022/05/gradle-laziness.html . Gradle hat zudem ein Beispiel-Plugin für Plugin Best Practices: https://github.com/gradle/gradle-site-plugin (ist halt mit Kotlin geschrieben, aber das Prinzip bleibt ja gleich). Da wird für den Custom Task ebenfalls die Property Api verwendet. 

Wichtig: Ich habe nirgends Informationen gefunden, dass Lazy Configuration forciert wird und alle Custom Tasks mit der Property oder Provider Api umgesetzt werden sollen. Es ist dem Plugin-Ersteller überlassen ob Eager oder Lazy Configuration bevorzugt wird. Die meisten Plugins scheinen aber zumindest einen Grossteil ihrer Funktionalitäten mittels Lazy Configuration zur Verfügung zu stellen.

Bezüglich deiner Aussage:

> Was ist was? Was führt zu welchen Problemen? Dann Entscheid, ob man auf diesen Zug auspringen will. Oder nur bei Bedarf (an einer einzigen Stelle vewenden wir bereits lazy configuration).

Das ist relativ schwierig so zu beantworten ohne die Tasks mal "testeshalber" umzustellen und zu schauen. Daher hier ein paar grundlegende Überlegungen, bevor wir mit der allfälligen Umsetzung starten:

A. Gibt es Tasks die sehr lange dauern und die man optimieren müsste? Vielleicht könnte man hier mal einen Test mit Lazy Configuration machen und schauen ob sich die Ausführungszeit verkürzt. (Ich kann gerade nicht einschätzen ob das verändern einzelner Tasks bereits ein Improvement ergeben oder ob man das erst merkt, wenn man Lazy all the way geht).
B. Wenn wir umstellen würden, dann müssten alle User sämtliche Tasks umschreiben, wenn sie auf die neuste Version von GRETL aktualisieren. 
Z.B. würde aus:

```
task av2geobau(type: Av2geobau){
    itfFiles = "ch_254900.itf"
    dxfDirectory = "./out/"
}
```

dann

```
task.register("av2geobau", Av2geobau){
    itfFiles.set("ch_254900.itf")
    dxfDirectory.set("./out/")
}
```

Ist das denn ein gangbarer Weg? Oder ist das nicht vorstellbar? 

### Mögliche Vorgehensoptionen, welche ich sehe
1. Ich würde auf sicherlich mal in den untenstehenden Files von task xY(type: ABC) auf Lazy Configuration wechseln (also task.register()). Das empfiehlt sogar meine IDE konstant. 😅
     - `gretl/build.gradle` 
     - `runtimeImage/build.gradle` 
     - `gretl/integration-test.gradle`
2. Falls Punkt B von oben gangbar ist, dann würde ich mit allfälligen Tasks aus Punkt A starten. Falls Punkt A keine bestimmten Tasks hervorbringt, dann könnte man mal mit den kleineren Tasks starten z.B. "Gzip", "Curl", "FtpList" etc. 
3. Anstelle einer kompletten Umstellung könnte man auch den Weg gehen, dass man einen Task, den man sowieso anpassen muss, gleich auch noch auf die Properties API umschreibt. So wäre der Aufwand etwas übersichtlicher und besser managebar. Andererseits kann es dann halt sein, das bestimmte Tasks nie umgeschrieben werden.

Sorry, das es wieder so lange geworden ist. 😂 Wir können auch gerne nächste Woche mal zusammen telefonieren und das besprechen, falls es dir lieber ist.

**Comment by Saela** [comment]
Besprechung 7.5.:

- Komplette Umstellung aktuell nicht nötig
- Blueprints erstellen für ein paar Tasks, damit Erfahrung mit Lazy Configuration gemacht werden kann:
   - SqlExecuter
   - Db2Db
   - IliToPgReplace
   - 1-2 Task bei denen [InputFile] Annotation durch [Input] getauscht werden musste. Kann so umgangen werden, dass das File existieren muss?

Ziel ist es Tasks für den User zu beschleunigen. Testlaufzeit oder Build-Zeit spielt keine grosse Rolle.
