### ISSUE TITLE
Java Update

### ISSUE THREAD

**Issue by Saela** [sogis/gretl#133]
**Currently used**: Java 8

> **DECISION:** Update to Java 11, move other tasks to backlog. Geotools are updated to be Java 17 compatible this year, so the upgrade to Java 17 has to wait anyways.

<details><summary>Additional Info</summary>
<p>
Java 21 LTS was released on 19.9.23. It would make sense to upgrade to the newest version if we are in the update process anyway.

This update also has to be done step by step so it is easier to find issues if there are any. 

**What we have to check for this ticket**:

The iox-wkf library is written in Java 8. This could be the main obstacle for an update to a newer Java version. 

**Open Questions**:
- If it would not be possible to use a newer Java version because the iox-wkf library cannot be used then:
	- Would it be possible to update the library? 
	- Is this library still needed or can be removed/replaced?
	- Is there another good solution to read or write Shape Files? If yes, iox-wkf could be replaced. See separate task: 
           https://github.com/orgs/sogis/projects/4/views/1?pane=issue&itemId=47530099
- What are we going to do if the library is not compatible with e.g. Java 21 and cannot be updated for certain reasons? Are we going to search for a replacement or just not do the Java update?

</p>
</details> 

Linked issues:

- #146 
- #147 
- #148

**Comment by edigonzales** [comment]
Muss-Projektziel sollte 11 sein. Weniger sprach-technisch, sondern dem Risiko vorzubeugen, dass gewisse Libs nicht mehr updatebar sind. Geotools wird eh erst dieses Jahr 17-fähig gemacht. Von daher erübrigt sich wohl 11-17 und 17-21.

Idee: iox-wkf ist momentan auf Java 8 limitiert. Man muss davon ausgehen, dass das so bleibt, weil das ganze Interlis-Universum Java 8 ist. D.h. wir können die höchste Geotools-Version verwenden, die sowohl Java 8 wie auch Java 11 fähig ist.

**Comment by Saela** [comment]
Ok, alles klar. Dann verschiebe ich die Tasks 147 und 148 in den Backlog.
