### ISSUE TITLE
Update JUnit4 to JUnit5 or use Spock

### ISSUE THREAD

**Issue by Saela** [sogis/gretl#134]
The decision on what to do is still open. We have to discuss if we should update to JUnit5 or use Spock. 

### JUnit5 Upgrade

Migration guide: https://www.baeldung.com/junit-5-migration

With JUnit Vintage we can even rewrite tests iteratively because we can run JUnit5 and JUnit4 tests in parallel.

**Comment by edigonzales** [comment]
#151 klares Bild bekommen und dann entscheiden. Auch wenn Spock erwähnt ist, dünkt mich das sehr aufwändig ohne wirklichen Benefit. Also Junit4 oder 5.

**Comment by Saela** [comment]
@edigonzales Ich verstehe nicht ganz, was du meinst mit "klares Bild bekommen und dann entscheiden". Entscheiden, ob wir auf JUnit5 gehen? Oder ob Spock doch sinnvoll wäre?

**Comment by edigonzales** [comment]
Ich _glaube_ , ich meinte, dass man anhand #151 die Beurteilung machen sollte. Beim Issue 151 geht es um die Homogenisierung des Testcodes. Wenn aufgrund von Erkenntnissen aus 151 Spock ein Gamechanger wäre, könnte man über Spock reden. Ansonsten denke ich, wird es junit bleiben.  Ob 4 oder 5? Auch das kann eventuell 151 helfen. Wenn man eh viel refactoren (um-/neuschreiben) will/muss, können wir gleich auf 5 gehen.

**Comment by Saela** [comment]
Aktionen:

- #151 Prüfen und Umsetzungsplan erstellen
- Je nach Resultat aus der Prüfung von #151 entweder Spock oder Junit5 einsetzen (siehe Kommentar oben)

**Comment by Saela** [comment]
@dkubanyi Could you please link your PR to this ticket as soon as you have one? You can do this by selecting the PR in the following issue setting (but you probably already know this :) ): 


![Image](https://github.com/sogis/gretl/assets/14041976/3417ab38-69af-4d58-aebd-23e28a6fe307)
