### ISSUE TITLE
Using test containers where possible

### ISSUE THREAD

**Issue by Saela** [sogis/gretl#136]
Currently no test containers are used for the integration tests. Where possible we should spin up test containers with pre-defined data/environment so we can have an isolated and reproducible tests. 

Where we should test with test containers and what to use here is still open for discussion. Though the Publisher-Simi-Server is explicitely mentioned in issue 109 on github. But I think nonetheless we should discuss the strategy here and what makes sense.

**Comment by edigonzales** [comment]
Ich denke vor allem auch an die S3-Geschichte. Hier können Tests nicht gemeinsam laufen, weil sie sich sonst im S3-Bucket in die Quere kommen. Localstack?

Beim Publisher-Simi-Server weiss ich nicht ganz genau was/wie getestet wird.

**Comment by Saela** [comment]
@edigonzales Wir werden hier in deiner Abwesenheit mal einen Plan ausarbeiten, wie man Testcontainer einsetzen könnte. Sind dir die S3 Tests wichtig, oder könnte man das alles lokal/in der Pipeline aufziehen?

**Comment by edigonzales** [comment]
Ja, die S3 Tests sind mir wichtig. Ggf mit https://java.testcontainers.org/modules/localstack/
