### ISSUE TITLE
Increase MaxParallelForks

### ISSUE THREAD

**Issue by Saela** [sogis/gretl#137]
There is a question in issue #109 about increasing the MaxParallelForks value. Because we use GithubRunners this increase is not really necessary/useful. GitHub Runners already handle parallelization out of the box quite well.

Should we still go for it? It might be beneficial for local runs...

**Comment by edigonzales** [comment]
Ich glaube man müsste mindestens diese maxParallelForks auf true setzen. Habe das nie gemacht. Siehe z.B. https://kousenit.org/2020/11/22/simple-demo-of-gradle-parallel-tests/ 
Weiss nicht wie das reagiert / zusammenarbeitet mit TestContainers.
