### ISSUE TITLE
Optimize build

### ISSUE THREAD

**Issue by Saela** [sogis/gretl#138]
**Analyze build logic**
To get more information about possible improvements we can run the github profiler on the build logic. 

**Possible Optimizations**

- Parallelize the tests in the build e.g. with a Test-Jobs-Matrix
- Decide if docker tests should run with every build or if they should only run on certain occasions like merging into main or e.g. a nightly run, setting a tag etc.

**Comment by edigonzales** [comment]
1. Soll der Dockerbuild weiterhin im gleichen Repo sein?
2. Sollen sämtliche Integration-Tests auch vom Docker-Image durchlaufen werden?

Die Antworten geben Anhaltspunkte, ob man mehr oder weniger am Test-Code ändern muss. Heute wird mit `Process p = Runtime.getRuntime().exec(command);` https://github.com/sogis/gretl/blob/master/gretl/src/integrationTest/java/ch/so/agi/gretl/util/IntegrationTestUtil.java#L55 sowohl das Plugin als Jar wie auch das Dockerimage aus dem Integrationstest aufgerufen. Wenn man z.B. zum Schluss kommt, dass nur noch das Plugin als Jar voll geprüft wird, könnte man dieses Process-Gedöns mit Buildin-TestKit-Zeugs ersetzen.

**Comment by Saela** [comment]
@edigonzales Wie willst du hier vorgehen um die Fragen zu beantworten? Brauchst du da einen Sparring-Partner oder hast du bereits eine klare Idee in welche Richtung du willst?

**Comment by edigonzales** [comment]
Weil es ja im AP4 ist, können wir den Sparring-Partner-Zug fahren. Dann ist die Codebase etc. viel besser bekannt.

**Comment by edigonzales** [comment]
Ich würde die Dockertests immer noch hier laufen lassen und auch alles durchlaufen lassen. Zudem wir jetzt einiges investiert haben, damit die Dockertests wieder mit Docker laufen (siehe #135) . 

Nachteile gibt es schon auch, aber die nehme ich momentan in Kauf:
- Dauer der Dockertests
- Komplexität (weil man argumentieren kann, dass das Herstellen des Dockerimages nicht dem eigentlichen Entwickler zumuten soll).
