### ISSUE TITLE
Usage of dynamic parameters

### ISSUE THREAD

**Issue by Saela** [sogis/gretl#139]
This also still needs to be specified. 

GRETL already uses dynamic parameters in certain places. But it still could be improved with e.g. environment specific configuration files. This can also be combined with the current implementation that is using project properties.

**Comment by edigonzales** [comment]
Da weiss ich gerade nicht, um was es geht?

**Comment by edigonzales** [comment]
@edigonzales Besser verstehen, was mich genau stört. Es geht um die Übergabe von Parameter vom Test-Code zum build.gradle des Testcases via Gradle-Property. Falls mich nichts mehr gross stört, sein lassen.

**Comment by edigonzales** [comment]
Schmerzt mich momentan nicht so sehr. Es ist anscheinend so transparent und stabil, dass auch externe Entwickler nicht darüberstolpern.
