### ISSUE TITLE
Backport to V_2_2_x: [Ili2pgImportSchema] expose createEnumTabsWithId (047efb7)

### ISSUE THREAD

**Issue by schmandr** [sogis/gretl#152]
Created a V_2_2_x branch.

Next steps:
* Configure workflow _.github/workflows/gretl.yml_:
  * In branch master: Tag with _latest_ only
  * In branch V_2_2_x: Don't tag with _latest_
* Backport commit 047efb7cf5b5d5a03108172e72e404a7d160c03e to branch V_2_2_x.

**Comment by edigonzales** [comment]
done https://github.com/sogis/gretl/commit/b69461f6a17e2a004a253a7a21a61d70653805ab
