### ISSUE TITLE
Docker Test Dauer nach Gradle Update verdoppelt

### ISSUE THREAD

**Issue by Saela** [sogis/gretl#161]
**Ausgangslage**
Nach dem Update auf Gradle 8.7 dauern die Integrationstests im Docker Container fast doppelt so lange. Das ist auch lokal zu beobachten. Die Tests liefen bereits mit Gradle 6 ca. 5-10 Minuten länger. 

**Mögliche Lösungsansätze**
- Die Integrationstests werden mit einem Custom Runner ausgeführt. Allenfalls ist es möglich dort zu optimieren?
- Was für einen Einfluss hat die Aktualisierung von Plugins? Momentan gibt es einige Dependencies, die out-dated sind.
- Gibt es grundsätzlich die Möglichkeit Tests im Docker Container zu parallelisieren? Dies würde zwar das grundlegende Problem nicht beheben, aber könnte als Zwischenlösung fungieren.

**Investigation**

Wenn mit die jarTests mit Gradle 8.7 laufen gelassen werden, dann kann dort bereits eine erhöhte Testlaufzeit festgestellt werden. Anhand von ShpValidatorTest -> validationFail kann dies folgendermassen aufgezeigt werden:

### Gradle 5.1.1 (aktuelle Version in master)

**Command:**
`./gradlew clean gretl:build gretl:publishPluginMavenPublicationToMavenLocal gretl:jarTest -x test --tests ch.so.agi.gretl.jobs.ShpValidatorTest.validationFail --profile` 

**Resultat: **

![Image](https://github.com/sogis/gretl/assets/14041976/e61d4ce6-92f7-42cb-8a7e-08fcab29faac)

### Gradle 8.7 (aktuelle version in gretl_3.0)

**Command**: 
`./gradlew clean gretl:build gretl:publishPluginMavenPublicationToMavenLocal gretl:jarTest -x test --tests ch.so.agi.gretl.jobs.ShpValidatorTest.validationFail --profile` 

**Resultat:**

![Image](https://github.com/sogis/gretl/assets/14041976/ec2438c5-b326-41ae-822b-1e900d7403b6)

Was auffällt:
- Reihenfolge der Tasks unterschiedlich
- compileJava dauert mehr als 1.5 Sekunden länger
- compileTestJava dauert mehr als 3 x so lange
- validatePlugins dauert zusätzlich ca 1s (gab es bei Gradle 5.1.1 noch nicht so)

Insgesamt dauert die Ausführung desselben Tasks in Gradle 8.7 fast doppelt so lange wie in Gradle 5.1.1

Mögliche Hinweise: https://github.com/gradle/gradle/issues/14877

**Comment by edigonzales** [comment]
@Saela Wobei entscheidend eigentlich nur :gretl:jarTest" wäre. In der realen Welt (beim Ausführen eine GRETL-Tasks) kompilieren wird ja nichts resp. können gar nichts komplieren, da java-Plugin nicht vorhanden ist.

**Comment by edigonzales** [comment]
Kannst --profile mit einem ganz einfachen build.gradle machen und dann die Startup-Zeit im Summary-Tab anschauen? Hier habe ich einen grossen Unterschied zwischen 5.1.1 und 8.5. Muss am besten nicht mal was mit GRETL zu tun haben, sondern bloss sowas:

```

task foo() {
  doLast{
    println "Hallo Welt."
  }
}
```

**Comment by edigonzales** [comment]
btw: GRETL-Tasks dauern bei uns in der Regel zwischen 30 Sekunden bis mehrere Minuten. Wenn es wirklich nur ein circa 3 Sekunden Penalty ist, würde es uns schlussendlich nicht sonderlich gross stören.

**Comment by Saela** [comment]
@edigonzales Ich habe mal, wie von dir vorgeschlagen, einen GRETL unabhängigen Test gemacht. 

**Gradle 5.1.1**


![Image](https://github.com/sogis/gretl/assets/14041976/cc5ff13f-2380-4f2e-8ab5-6a118e8315d9)

**Gradle 8.7**


![Image](https://github.com/sogis/gretl/assets/14041976/4a2a8623-533e-47fa-a503-71200f399662)

Es zeigt sich eigentlich das gleich Muster, wie oben im Ticket beschrieben. Das Setup des Projekts mit Gradle 8.7 dauert doppelt so lange. Dafür ist aber hier bei Gradle 5.1.1 zu sehen, dass der Startup länger dauert. Alles in allem hebt sich das aber wieder auf, wenn man die Total Build Time anschaut.

Was hattest du für Ergebnisse?

**Comment by Saela** [comment]
Per Zufall habe ich mir nochmals die Task Configuration angeschaut und bin über die Task configuration avoidance api gestolpert: https://docs.gradle.org/current/userguide/task_configuration_avoidance.html

Das könnte die Konfigurations/Startup Time auch verkürzen. Ich würde das mal testen.

**Comment by edigonzales** [comment]
@Saela So, ich hab es durchschaut. Integrationstest dauern nur noch 10 Minuten und nicht mehr 30: Anscheinend macht Gradle beim Starten mit jeder Version immer mehr oder anders (bereits Gradle 6 war ja langsamer). Mit Gradle 8 wird auch enorm viel in die Konsole geloggt (im Lifecycle-Level). Das auch der Grund warum ich momentan auf der letzten 7er-Version bin. Dieser Logoutput hat mich aber auf die Lösung gebracht. Jede Jar-Datei, die durch Plugins eingebunden werden (und das sind ja viele bei uns) werden geprüft oder so ähnlich und das Resultat dieser Prüfung gecacht. Der Cache liegt im $HOME/.gradle, das aber beim Docker Run nicht persistiert wird. Somit verlieren wir jeweils bei jedem Test circa 15 Sekunden oder so. D.h. ich musste nur das Verzeichnis persistieren für die Integrationstests mit Docker.

**Comment by Saela** [comment]
@edigonzales Yeah, sehr nice hast du das rausgefunden! 🎉🎉😎
