### ISSUE TITLE
Upgrade to newest Gradle version if possible

### ISSUE THREAD

**Issue by Saela** [sogis/gretl#170]
Gradle 8.8 is out. If we are on it anyways I suggest to upgrade Gradle to the newest version. :)

**Comment by edigonzales** [comment]
Wenn es nicht noch langsamer wird ;)

**Comment by dkubanyi** [comment]
~~Gradle 8.8 requires Java 22~~ - https://docs.gradle.org/current/userguide/compatibility.html
Edit: it's actually the other way around :)

**Comment by Saela** [comment]
Changes Anschauen und allenfalls gleich auf Gradle 8.10 (neuste Version), falls nicht viel geändert werden muss.

**Comment by edigonzales** [comment]
Momentan auf Version 7 bleiben. Gradle 8 macht im Lifecycle-Loglevel enorm viel Output. Wird erst relevant, wenn wir auf Java 21 wechseln müssen/wollen.
