### ISSUE TITLE
FTP-Task

### ISSUE THREAD

**Issue by edigonzales** [sogis/gretl#32]
Implementieren eines FTP-Tasks. Vorhandene funktionieren nur unter gewissen Bedingungen (sftp) oder funktionieren mit wohl bekannten FTP-Servern nicht...

Task mit FTP als Code:
- https://github.com/sogis/gretljobs/blob/master/arp_fledermaus/build.gradle
- Mocheckso: Download von Infogrips-Server (not yet implemented)

**Comment by claeis** [comment]
Soll der FtpDownload Task 
a) die Remote Files löschen (nach dem download)?
b) das lokale Verzeichnis erstellen (wenn es noch nicht existiert)?
c) geht er wie implementiert mit dem Infogrips-Server?

**Comment by edigonzales** [comment]
a) Als Option. 
b) Nein. Finde ich nicht nötig.
c) Nein. Siehe https://github.com/sogis/gretl/commit/ec64bda5b878db05b3841a0bf223287ccce41496#diff-3efa42ccba64c9c192946072c80a9a8e0b03eb0add63da84aa21d9bcd28a2a80 Grösstes Problem ist die `mlistDir`-Methode, die anscheinend nichts zurückliefert und die `retrieveFile`-Methode, wo der Filenamen alleine nicht reicht. Explizit `systemTypeKey` auf `WINDOWS` setzen, war glaub früher notwendig bei Infogrips. Jetzt scheint es auch ohne zu funktionieren. Was nicht geht ist `UNIX`. Weiss jetzt nicht, ob man es überhaupt brauchen sollte als Option? Der Fileseparator "/" beim File retrieven ist wohl "best guess" und scheint praktisch immer zu funktionieren. Standardisiert scheint es nicht zu sein.
Beispiel-Task: https://github.com/sogis/gretljobs/blob/avimport/agi_av_import/build.gradle

**Comment by edigonzales** [comment]
d) Einzelnes File herunterladen?
