### ISSUE TITLE
Db2Db Task: Manchmal Fehlermeldung, wenn Umlaute im SQL-Skript vorkommen

### ISSUE THREAD

**Issue by schmandr** [sogis/gretl#4]
Wenn man das angehängte SQL-Skript [awjf_biotopbaeume_pub_biotopbaeume_biotopbaum.sql.txt](https://github.com/sogis/gretl/files/2894261/awjf_biotopbaeume_pub_biotopbaeume_biotopbaum.sql.txt) in einem Db2Db Task verwendet, Meldet GRETL:

```
Exception while executing processAllTransferSets()
ch.so.agi.gretl.util.GretlException: Wrong encoding (not UTF-8) detected in File /home/gradle/project/awjf_biotopbaeume_pub_biotopbaeume_biotopbaum.sql
```

Gemäss Noemi hat es damit zu tun, dass der Db2Db Task das SQL-Skript in mehreren Teilen einliest; wenn am Ende eines solchen Teils der Datei ungünstigerweise gerade ein spezielles Zeichen wie ein Umlaut steht, kommt es zu dieser nicht ganz präzisen Fehlermeldung.

Workaround ist, irgendwo eher am Anfang der Datei z.B. einen Leerschlag einzufügen.

**Comment by edigonzales** [comment]
https://github.com/sogis/gretl-v1/issues/145

**Comment by edigonzales** [comment]
[awjf_biotopbaeume_pub_biotopbaeume_biotopbaum_ok.sql.zip](https://github.com/sogis/gretl/files/2970232/awjf_biotopbaeume_pub_biotopbaeume_biotopbaum_ok.sql.zip)
[awjf_biotopbaeume_pub_biotopbaeume_biotopbaum_fail.sql.zip](https://github.com/sogis/gretl/files/2970234/awjf_biotopbaeume_pub_biotopbaeume_biotopbaum_fail.sql.zip)

**Comment by edigonzales** [comment]
https://stackoverflow.com/questions/499010/java-how-to-determine-the-correct-charset-encoding-of-a-stream/4013565#4013565

**Comment by edigonzales** [comment]
Sollte mit https://github.com/sogis/gretl/commit/bf9345b40316f125616af82e2cb923b9f68c5e1b und https://github.com/sogis/gretl/commit/965bfe9a963a58b6f47f2bd46e469d53e05ce5bd gefixed sein.

Nach Versuchen mit Drittbibliotheken (falsche Resultate, Geotools-Probleme) lese ich jetzt einfach das ganze File in den Buffer. Bei _unseren_ Filegrössen spielt das keine Rolle.
