### ISSUE TITLE
Task S3Upload

### ISSUE THREAD

**Issue by barpasen** [sogis/gretl#40]
Beim lokalen Ausführen des Tasks S3Upload im Gretl-Job "oereb_einzelschutz_denkmal (importDataToStage)" kommen neu folgende Meldungen:
Start S3UploadStep(Name: null SourceObject: /tmp/oerebadaeinzelschutz-6268367163714977833 BucketName: ch.so.ada.denkmal S3EndPoint: https://s3.amazonaws.com/ S3Region: eu-central-1 ACL: PublicRead MetaData: {})
No content length specified for stream data.  Stream contents will be buffered in memory and could result in out of memory errors.
No content length specified for stream data.  Stream contents will be buffered in memory and could result in out of memory errors.
No content length specified for stream data.  Stream contents will be buffered in memory and could result in out of memory errors.
...
...
...
null: 603 Files have been uploaded to: ch.so.ada.denkmal.

Der Gretl-Job läuft sonst ohne Fehler durch, Die Pdf's werden hochgeladen. Das war zu Beginn noch nicht so, als es nur den Bucket "ch.so.ada.denkmal" gab.

**Comment by edigonzales** [comment]
fixed https://github.com/sogis/gretl/commit/35cde593f6d997d31b5b8c4b0f9b6bbc1d6ced26
