### ISSUE TITLE
PostgreSQL Client wieder ins Runtime Image installieren

### ISSUE THREAD

**Issue by schmandr** [sogis/gretl#48]
Den PostgreSQL Client, der mit baafb45 aus dem Runtime Image gefallen ist, bräuchte ich wieder. Dies, damit mit dem GRETL Runtime das ÖREB-DB-Image getestet werden kann, was nun fehlschlägt: https://github.com/sogis/oereb-db/pull/32/checks?check_run_id=1784823520. Denn das GRETL Runtime prüft mit `pg_isready` (das ist Teil des PostgreSQL Clients), ob die DB schon für die Tests bereit ist.

Ist irgendwie zwar schon fraglich, ob es keine bessere Möglichkeit gibt. Wie ich mich erinnere, hatte ich am Anfang einfach ein simples `sleep `von einigen Sekunden drin. Was meinst du?

**Comment by edigonzales** [comment]
https://github.com/sogis/gretl/commit/330b4c749abc75c794e8e4c7f6c35ad05aafc3ef
