### ISSUE TITLE
iox-wkf version from interlis.ch repo

### ISSUE THREAD

**Issue by edigonzales** [sogis/gretl#50]
Pull request wurde gemerged. Man kann wieder die Original-Version von iox-wkf verwenden.

**Comment by schmandr** [comment]
Ah, zum Glück, denn Bintray ist nun wirklich abgeschaltet, und deshalb ist auch der letzte Build fehlgeschlagen: https://github.com/sogis/gretl/runs/2631415953?check_suite_focus=true

**Comment by schmandr** [comment]
@edigonzales kannst du dies in Bälde umsetzen, damit die Builds (Actions) wieder funktionieren?

**Comment by edigonzales** [comment]
fixed https://github.com/sogis/gretl/commit/68ddccb65c794fd6ee3c2f87e3a399c619f5068f
