### ISSUE TITLE
Error when running gretl-local on Linux x86_64

### ISSUE THREAD

**Issue by schmandr** [sogis/gretl#57]
Wenn ich _gretl-local_ auf meiner x86_64-Linux-Maschine ausführen möchte, kriege ich:

```
Status: Downloaded newer image for sogis/gretl-local:latest

FAILURE: Build failed with an exception.

* What went wrong:
Failed to load native library 'libnative-platform.so' for Linux amd64.
```

`docker image inspect sogis/gretl-local` gab mir schon irgendwo aus: `"Architecture": "amd64"`

**Comment by edigonzales** [comment]
Was ist genau der Befehl? Fehlermeldung kommt mir bekannt vor. Es ist glaubs irgendwas mit den Permissions. Jedenfalls muss ich zwingend `--user $UID` weglassen.

**Comment by edigonzales** [comment]
@schmandr Beim vorherigen Kommentar noch unsicher aber ich hatte ein README nicht überall nachgeführt. Ich muss z.B. auch einen leicht anderen Aufruf machen:

```
docker-compose run --rm -v $PWD/development_dbs:/home/gradle/project gretl "sleep 20 && cd /home/gradle/project && gretl -b build-dev.gradle importResponsibleOfficesToOereb"
```

vs

```
docker-compose run --rm --user $UID -v $PWD/development_dbs:/home/gradle/project gretl "sleep 20 && cd /home/gradle && gretl -b project/build-dev.gradle importResponsibleOfficesToOereb"
```

Ich muss ins Projektverzeichnis wechseln (`cd`), sonst kommt die gleiche Fehlermeldung. Die "normalen" Aufrufe sind aber gleich (oder?). Am start-gretl.sh habe ich glaubs nix geändert:

```

./start-gretl.sh --docker-image sogis/gretl-local:latest --docker-network oereb-gretljobs_default --job-directory $PWD/oereb_bundesgesetze downloadData importData
```

Bei mir gibts so hässlich `?`-Verzeichnisse. Ist/war für mich ein Indiz, dass es noch besser geht. Irgendwie hängt wahrscheinlich schon bissle alles zusammen, sprich irgendwas mit den Permissions.

**Comment by schmandr** [comment]
Auch mit einem simplen
`docker run -i --rm --name gretl sogis/gretl-local:latest gradle`
wurde derselbe Fehler gemeldet.
Mit  
`docker run -i --rm --name gretl sogis/gretl-local:latest sleep 600`
konnte ich den Container aber mal starten und reinschauen.

Der Post https://stackoverflow.com/a/58548374 liefert möglicherweise die Antwort: Dem User _gradle_ gehört zwar das Verzeichnis `/home/gradle/.gradle`, aber auf `/home/gradle/.gradle/native` hat er keine Schreibrechte:

```
/home/gradle $ ls -la /home/gradle/.gradle
total 12
drwxr-sr-x    3 gradle   gradle        4096 Jan 28 08:58 .
drwxr-sr-x    1 gradle   gradle        4096 Jan 18 14:00 ..
drwxr-sr-x    4 root     gradle        4096 Jan 28 08:58 native

```

Das kommt wohl entweder von https://github.com/sogis/gretl/blob/15423c2ad40e70983835e2c062441fba7b4c15ac/runtimeImage/gretl/Dockerfile.local#L20
oder von https://github.com/sogis/gretl/blob/15423c2ad40e70983835e2c062441fba7b4c15ac/runtimeImage/gretl/Dockerfile.local#L43

Evtl. nützt es etwas, den Test, ob Gradle läuft, erst nach der Zeile
`USER 1001`
auszuführen, damit die Dateien diesem User gehören.

**Comment by edigonzales** [comment]
Mmmh, eh sehr komisches Verhalten bei mir: `dbUriOerebV2` findet er nicht beim docker-compose-Aufruf. Das ist jetzt eben weil ich ins Projekt-Verzeichnis wechsle und die Properties nicht injiziert werden? Aber warum funktioniert es mit dbUriEdit? Ich checke mal USER 1001.

**Comment by edigonzales** [comment]
Oh nein. Mein Propertiesproplem ist was profaneres. Wenn ich mit docker-compose arbeite, müssen sie natürlich im docker-compose file sein.

**Comment by schmandr** [comment]
Sehr gut, jetzt funktioniert es bei mir auch. Auch mit `--user $UID`.

An `start-gretl.sh` habe ich die notwendigen Anpassungen gamcht und in den Branch https://github.com/sogis-oereb/oereb-gretljobs/tree/gretl_wrapper_script eingecheckt. Er ist primär mal zur Dokumentation dort, aber du kannst ihn auch mergen, damit du `start-gretl.sh` mit `gretl-local` verwenden kannst.

**Comment by schmandr** [comment]
Mir wird nun ebenfalls ein Verzeichnis `.gradle` und ein Verzeichnis `?` im GRETL-Job-Verzeichnis angelegt. Ersteres ist wohl normal. Letzteres schaue ich mir noch genauer an.

**Comment by schmandr** [comment]
Bezüglich dem Verzeichnis `?` hatte ich die Vermutung, dass es daran liegt, dass keine `$HOME` definiert ist. Aber es liegt wohl nicht daran.

Meine momentane Erklärung ist: Ich habe auf meiner lokalen Maschine die UID 1000. In _gretl-runtime_ gibt es den User _default_, der ebenfalls die UID 1000 hat. Wenn ich nun den Container mit `--user $UID` starte, passt das zufällig zusammen, und Gradle kann einen gewissen Teil ins Home des Users _default_ schreiben (das ist /home/jenkins).
Wenn wir nun _gretl-local_, wo es keinen User mit UID 1000 gibt, mit `--user $UID` starten, findet Gradle keinen passenden User und kein passendes Home. Deshalb schreibt es das Zeug ins Projektverzeichnis. Und weil es keinen passenden Usernamen zur UID 1000 findet, legt es einen Ordner mit der Bezeichnung `?` an.

(Dass _gretl-local_ auch mit `--user $UID` läuft, stimmt mich übrigens optimistisch, dass es auch in OpenShift läuft.)

**Comment by edigonzales** [comment]
Hat sich m.E. erledigt. gretl-local gibt es nicht mehr. Ist alles mehr oder weniger ins "normale" Gretl geflossen.
