### ISSUE TITLE
Baseline für den merge

### ISSUE THREAD

**Issue by ojeker** [sogis/gretl#70]
Frage: Wie verschaffe ich mir einen Überblick über alle Tests, welche vor dem Publisher vorhanden sind (Auf dem Master)?

Umfasst `./gradlew build` alle Unit- und Integrationstests?

Beim Ausführen von `./gradlew build` erhalte ich den unten folgenden Fehler. Kann dieser vor dem Merge ausgemerzt werden?

```
./gradlew build

> Task :gretl:compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :gretl:test

ch.so.agi.gretl.steps.Gpkg2ShpStepTest > export_Ok FAILED
    java.lang.ExceptionInInitializerError at Gpkg2ShpStepTest.java:33
        Caused by: java.lang.IllegalArgumentException at Gpkg2ShpStepTest.java:33

41 tests completed, 1 failed
```

**Comment by edigonzales** [comment]
Nein. Jedenfalls weiss ich ad hoc nicht wie. Ist glaub ein Java-Versionsproblem. Mit Java 8 funktionierts. Warum genau dieser Test nicht funzt, weiss ich nicht. Ich habe mich nie darum gekümmert, da wegen Uralt-Geotools-Version glaub sowieso Java 8 als Runtime gesetzt ist.

**Comment by edigonzales** [comment]
Ah und zur Frage wegen den Tests: Ich glaube nicht. Siehe v.a. das gretl.yml der Github Action. Im Kern stammt der Aufbau (Trennung zwischen test und jarTest) noch von euch:

- Unit-Tests: `./gradlew gretl:test gretl:dbTest`. Die Kategorie "dbTest" sind PostgreSQL-Tests, welche das Hot-Shit-Meccano verwenden (weil eben externe Abhängigkeit).
- Integrationstests: `./gradlew gretl:jarTest` und `./gradlew gretl:jarS3Test ..... jarS3Test ist eine eigene Kategorie, welche nach S3 schreibt. Diese sind bissle hakelig, weil die sauber aufräumen müss(t)en. Hier sollte man mal auf Localstack oder so wechseln.

Anschliessend werden die Integrationstests noch mit dem Docker-Image durchgenudelt.

**Comment by edigonzales** [comment]
btw: 
- https://github.com/sogis/gretl#unit-tests
- https://github.com/sogis/gretl#integration-tests
- https://github.com/sogis/gretl#s3-tests

**Comment by claeis** [comment]
Ich habe an der Testkonzeption nichts geändert.
Die Hauptfunktionalität des Publishers wird getetstet durch: PublisherStepDb2LocalTest, PublisherStepFile2LocalTest, PublisherStepFile2RemoteTest (alle in gretl/src/test/java/ch/so/agi/gretl/steps)

**Comment by ojeker** [comment]
OK - danke. Ist mir nicht in den Sinn gekommen, dass ich bei der Github-Action spicken kann. Und danke für die Info zu den Publisher Tests.
