### ISSUE TITLE
Copy-paste bug detected for new `createDateTimeChecks` option

### ISSUE THREAD

**Issue by schmandr** [sogis/gretl#76]
https://github.com/sogis/gretl/blob/6ae664e002fc1e1cbb5021b6059cad562a7f71b3/gretl/src/main/java/ch/so/agi/gretl/tasks/Ili2pgImportSchema.java#L264-L265

**Comment by edigonzales** [comment]
fixed https://github.com/sogis/gretl/commit/99b74c9ce66837bd5074bfadce651024fa15d5c5
