### ISSUE TITLE
Publisher-Task: Provider "sftp" not found

### ISSUE THREAD

**Issue by barpasen** [sogis/gretl#77]
task publishFile1(type: Publisher) {
  dataIdent = "ch.so.agi_hoheitsgrenzen_publishFile1"
  sourcePath = file("ch.so.agi_hoheitsgrenzen_pub_v1.xtf")
  target = [ "sftp://sftp.geo.so.ch/gretl-test/data", testSftpUser, testSftpPwd ]
}
> What went wrong: Execution failed for task ':publishFile1'. > Provider "sftp" not found

 Der Gretl-Job läuft lokal mit image sogis/gretl:latest. Der FTP-Server ist lokal vom Terminal erreichbar.

**Comment by ojeker** [comment]
@claeis Fehlen da noch Dependencies im Image? Anderer Grund?

**Comment by claeis** [comment]
vermutlich fehlt com.github.robtimus:sftp-fs:2.0.4

**Comment by schmandr** [comment]
Das .jar scheint immerhin vorhanden zu sein. Im Build des Images wird jeweils ein `ls -la /home/gradle/libs` gemacht, und im aktuellsten Build wird folgendes Jar gelistet: https://github.com/sogis/gretl/actions/runs/3054088587/jobs/4925540214#step:19:650

**Comment by barpasen** [comment]
@claeis ohne Docker Image getestet, gleiche Fehlermeldung: Provider "sftp" not found.
mit Option --stacktrace: Caused by: java.nio.file.ProviderNotFoundException: Provider "sftp" not found

- Gradle lokal installiert (sdkman)
- siehe Bsp: [https://github.com/sogis/gretl/blob/master/docs/user/index.md#kleines-beispiel]. gretl-plugin-Version 2.2.+ 

build.gradle

```
import ch.so.agi.gretl.tasks.*
import ch.so.agi.gretl.api.*
import java.nio.file.*

buildscript {
    repositories {
        maven { url "https://jars.interlis.ch" }
        maven { url "https://jars.umleditor.org" }
        maven { url "https://repo.osgeo.org/repository/release/" }
        maven { url "https://plugins.gradle.org/m2/" }
        mavenCentral()
    }
    dependencies {
        classpath group: 'ch.so.agi', name: 'gretl',  version: '2.2.+'
    }
}
defaultTasks "publishFileSftp"

task publishFile1(type: Publisher) {
  dataIdent = "ch.so.agi_hoheitsgrenzen_publishFile1"
  sourcePath = file("ch.so.agi_hoheitsgrenzen_pub_v1.xtf")
  target = [ "sftp://sftp.geo.so.ch/gretl-test/data", testSftpUser, testSftpPwd ]
}
```
Kannst du das nochmal testen, wir bringen das nicht zum laufen, gemäss Oliver sollte das bis spätestens 24. Okt. gefixt sein

**Comment by edigonzales** [comment]
```
Caused by: java.nio.file.ProviderNotFoundException: Provider "sftp" not found
```

So wie ich FileSystems verstehe, müsste der Provider im Classpath sein und es sollte funktionieren. Als Dependency ist es ja definiert. Komisch. Man muss prüfen, ob es zur Laufzeit tatsächlich im Classpath ist.

**Comment by edigonzales** [comment]
```
task showClasspath() {
    doLast() {
        buildscript.configurations.classpath.each { println it }
    }
}
```

Hier wird sftp-fs aufgelistet. Wenn ich aber den Classpath im PublisherTask, direkt vor `FileSystems.newFileSystem( host, environment );` ausgebe `System.out.println(System.getProperties().get("java.class.path"));`, zeigt es mir nur "/Users/stefan/.sdkman/candidates/gradle/5.4.1/lib/gradle-launcher-5.4.1.jar".

Vielleicht liegt hier der Hund begraben. Ich weiss nicht genau wie das Meccano mit dem FileSystemProvider / ServiceProvider funktioniert.

**Comment by edigonzales** [comment]
@barpasen @claeis Sollte mit https://github.com/sogis/gretl/commit/f385deb3a2520d78cfc94d8826b9b6c36b145eb8 gefixed sein.

Ich kann aber mit einem lokalen SFTP (https://hub.docker.com/r/atmoz/sftp) nicht einloggen. Ziel: Integrationstest. Es erscheint immer die Fehlermeldung `java.nio.file.FileSystemException: UnknownHostKey: localhost. RSA key fingerprint is 2e:23:11:10:ec:83:ef:46:54:64:66:a2:31:d8:0c:0a`. Mit Cyberduck funktioniert das Einloggen. Vielleicht funktioniert es mit unserem Prod-SFTP? Sonst neues Ticket erstellen. Ich verstehe das ganze Key-Knownhosts-Geschmeus noch nicht so wirklich. GRETL erwartet anscheinend ein known_hosts file: https://github.com/sogis/gretl/blob/master/gretl/src/main/java/ch/so/agi/gretl/tasks/Publisher.java#L152

z.K. @schmandr @ojeker

**Comment by edigonzales** [comment]
https://robtimus.github.io/sftp-fs/index.html

**Comment by schmandr** [comment]
Die Verbindung zu unserem produktiven SFTP-Server funktioniert auch nicht ohne Eintrag in `known_hosts`:
`java.nio.file.FileSystemException: UnknownHostKey: sftp.geo.so.ch. RSA key fingerprint is 3f:ac:c3:dc:0f:31:95:7c:43:ee:10:a9:1a:ff:9c:6d`

Ich habe mit `ssh-keyscan -t rsa -H HOSTNAME` den Public Key des Servers abgefragt und in meinem `known_hosts` eingetragen. Dann lief (lokal, nicht im Docker Container) der Task etwas weiter. Nun kommt aber die Meldung:

```
failed to run Publisher
java.lang.NullPointerException
        at java.base/java.lang.StringBuilder.<init>(StringBuilder.java:128)
        at com.github.robtimus.filesystems.sftp.SFTPFileSystem.getPath(SFTPFileSystem.java:161)
        at com.github.robtimus.filesystems.AbstractPath.resolve(AbstractPath.java:96)
        at com.github.robtimus.filesystems.sftp.SFTPPath.resolve(SFTPPath.java:115)
        at com.github.robtimus.filesystems.sftp.SFTPPath.resolve(SFTPPath.java:54)
        at ch.so.agi.gretl.steps.PublisherStep.publishFilePre(PublisherStep.java:497)
        at ch.so.agi.gretl.steps.PublisherStep.publishDatasetFromFile(PublisherStep.java:423)
        at ch.so.agi.gretl.tasks.Publisher.publishAll(Publisher.java:202)
```

**Comment by schmandr** [comment]
Im Docker Container habe ich die Geschichte mit dem `known_hosts` nicht zum laufen gekriegt. Wahrscheinlich, weil das `user.home` nicht definiert ist, weil es den User `1001` im Container nicht gibt.

Falls wir ohne das `known_hosts` nicht auskommen, würde ich es übernehmen, den Docker Container so umzubauen, dass im Container der entsprechende User angelegt wird.

**Comment by edigonzales** [comment]
@barpasen Kannst du ein neues Ticket machen und @claeis zuweisen (wegen Fehlermeldung von Andi), falls du es nicht zum Laufen kriegst? Vielleicht fehlt noch was in der Task-Konfiguration.

**Comment by schmandr** [comment]
Die `java.lang.NullPointerException` kommt offenbar deshalb, weil ich vorher beim Experimentieren zu viele fehlgeschlagene Anmeldeversuche produziert habe. (Bei manueller Anmeldung am Server kommt nämlich jetzt: Too many authentication failures.) Von Peters Maschine aus hat der SFTP-Upload in Kombination mit dem Eintrag in `known_hosts` dann endlich funktioniert.

Dann passe ich nun den Container an:
* User im Container anlegen
* entsprechende Zeile in `known_hosts` bereitstellen

**Comment by claeis** [comment]
known_hosts ist notwendig, wegen: _This will be used when connecting remote servers to check that their public keys are the same as we think they should be._

**Comment by schmandr** [comment]
OK.

@claeis Was ist deine Einschätzung zu unserer Idee, das known_hosts mit dem Eintrag für diesen Server direkt ins Image zu packen? Wäre es kein Problem bezüglich Sicherheit? Gleichzeitig dünkt es mich, dass es nicht die "richtige" Lösung ist. Vorteil wäre halt, dass unsere GRETL-Job-Entwickler sich nicht darum kümmern müssen, das known_hosts zu generieren und in den Container zu mounten.

**Comment by claeis** [comment]
dünkt mich ok

**Comment by schmandr** [comment]
In Arbeit im Branch https://github.com/sogis/gretl/tree/runtimeImage_adduser

**Comment by schmandr** [comment]
Jetzt besteht noch die Herausforderung, dass das mit dem `known_hosts` lokal zwar funktioniert, wenn der Docker Container als der User 1001 ausgeführt wird. Wir führen ihn aber mit der UID des Benutzers, der den Container startet, aus, damit in die gemounteten Volumes geschrieben werden kann. Und weil es diesen User im `/etc/passwd` des Containers nicht gibt, ist für ihn kein `user.home` definiert. Das sieht man, wenn man `docker run --user $UID --rm --name gretl sogis/gretl:latest java -XshowSettings:properties -version` ausführt.

Ich glaube, das kriege ich noch hin, indem man lokal dem gretl-Befehl jeweils zusätzlich `-Duser.home=/home/gradle` übergibt.
In OpenShift wird es voraussichtlich auch ohne diese Option funktionieren, weil OpenShift in `/etc/passwd` einen Eintrag für den generischen User macht.

**Comment by schmandr** [comment]
Bereit in #86

**Comment by barpasen** [comment]
@schmandr ich habe den Eintrag im known_hosts bei mir lokal wieder entfernt, das Kopieren auf den SFTP-Server hat funktioniert.

**Comment by schmandr** [comment]
@barpasen Sehr schön! Dann können wir dieses Ticket schliessen.
