### ISSUE TITLE
export via Modellname statt via Baskets, Datasets

### ISSUE THREAD

**Issue by barpasen** [sogis/gretl#78]
task publishFromDb7(type: Publisher) {
    database = [dbUriPub, dbUserPub, dbPwdPub]
    dataIdent = "ch.so.agi_hoheitsgrenzen_publishFromDb7"
    dbSchema = "agi_hoheitsgrenzen_pub"
    target = [project.buildDir]
    modeldir = "http://models.geo.admin.ch/;http://geo.so.ch/models"
    userFormats = true
}

* What went wrong:
Execution failed for task ':publishFromDb7'.
> dataset OR region OR regions must be set

Sollte das nicht auch ohne "dataset", "region" oder "regions" gehen, wenn das DB-Schema ohne createBasketCol  und createDatasetCol erstellt wurde?

**Comment by claeis** [comment]
Die DB muss mit createBasketCol erstellt werden und einer der Parameter dataset, region, regions muss angegeben werden

**Comment by ojeker** [comment]
> Die DB muss mit createBasketCol erstellt werden und einer der Parameter dataset, region, regions muss angegeben werden

Hoi Claude. Der Spezialfall "dataset" und "region" funktioniert tip-top. Es ist aber eben der Spezialfall. Der Normalfall, sprich ohne Angabe von dataset, region, regions muss auch funktionieren.

**Comment by claeis** [comment]
Der Fall mit dem Modelnamen ist keine gute Idee, weil man damit, ohne dass man das Modell genau kennt, zu einfach zuwenig (falls man ein kantonales Rucksackmodell zu einem Bundes-Modell hat) oder zuviel Daten (falls z.B. Codelisten im gleichen Modell modelliert sind) publizieren kann.

**Comment by ojeker** [comment]
Verstehe den Bezug dieses Issue zu Modellnamen nicht. Hier geht es um region, basket, dataset...? Hab das Issue umgenannt, damit dies in der Übersicht auch gleich klar wird.

**Comment by claeis** [comment]
Bei Export via Modellname: Der Publisher prüft, dass die DB nur Objekte aus dem gegebenen Modell enthält und bricht sonst mit einem Fehler ab.

**Comment by claeis** [comment]
neuer Parameter "models"

**Comment by claeis** [comment]
Schutz, dass nur bei einfachem Modell publiziert wird, benötigt claeis/ili2db#487

**Comment by ojeker** [comment]
Frage von Claude (per Email):
der export via modellname ist schnell gemacht, aber der Schutz, dass man das nur kann, wenn es ein einfaches Modell ist, ist aufwändig zu implementieren.

Soll ich den export via modellname trotzdem (also ohne Schutz) rasch machen, damit ihr weiterkommt?

Antwort: Ja, wäre eine gute Sache

**Comment by ojeker** [comment]
Braucht es den neuen Parameter "models", oder reicht das Weglassen von dataset resp. basket? Falls "models" notwendig bitte in der Doku ergänzen wofür.

**Comment by claeis** [comment]
Es braucht den neuen Paramter, damit der Benutzer sich bewusst ist, was er macht.

**Comment by claeis** [comment]
neuer Parameter ist modelsToPublish

**Comment by barpasen** [comment]
Funktioniert mit modelsToPublish
