### ISSUE TITLE
Regionen

### ISSUE THREAD

**Issue by barpasen** [sogis/gretl#79]
Hier braucht es unbedingt ein konkretes Beispiel, da für mich überhaupt nicht ersichtlich ist, wie das funktionieren soll.
Wie/wo sind die Regionen definiert?

**Comment by ojeker** [comment]
@barpasen Was hast du bereits ausprobiert? Wie ist der besprochene Test mit der Nutzungsplanung rausgekommen?

**Comment by barpasen** [comment]
@ojeker 
In der DB sind im Schema Nutzungsplanung 3 datasets vorhanden: 2580, 2581, 2582
Mein Testfile:
task publishFromDb8(type: Publisher){
    dataIdent = "ch.so.arp.nutzungsplanung.publishFromDb8"
    database = [dbUriPub, dbUserPub, dbPwdPub]
    dbSchema = "arp_nutzungsplanung_pub_v1"
    modeldir = "http://models.geo.admin.ch/;http://geo.so.ch/models"
    target = [project.buildDir]
    
    //region = "[0-9][0-9][0-9][0-9]"                                 // das geht alles nicht!
    //region = "[0-9][0-9]"
    //region = "[2][5]"
    //region = "2580

    dataset = "2580"                                                       // das geht
}

Vielleicht kannst du mir Anhand dieses Beispiels erläutern, wie das funktionieren soll, ich verstehe das nicht!
