### ISSUE TITLE
Publisher.kgdiService: Erweiterung des PUT-Requests

### ISSUE THREAD

**Issue by ojeker** [sogis/gretl#80]
Hoi Claude

Zwecks Validierung möchten wir den PUT-Request des kgdiService mit dem Namen des Exportmodells erweitern. 

Json-Payload mit neuem Attribut "exportModel":

```json
{
	"dataIdent": "ch.so.afu.gewaesserschutz",
	"published": "2021-12-23T14:54:49.050062",
	"publishedBaskets": [{
		"model": "SO_AGI_MOpublic_20201009",
		"topic": "Bodenbedeckung",
		"basket": "olten"
	}, {
		"model": "SO_AGI_MOpublic_20201009",
		"topic": "Bodenbedeckung",
		"basket": "wangen"
	}],
	"partIdentifiers": ["224", "225"]
}
```

Der Service Antwortet mit einem HTTP Status-Code 422, falls die serverseitige Validierung fehlschlägt.

Fragen:
* Falls im build.gradle exportModels nicht angegeben wird: Wie findet der Publisher heraus, nach welchem Modell exportiert werden soll?
* exportModels: Wieso Mehrzahl?
* Passiert heute etwas mit dem Content der Response des PUT-Requests? Etwa Schreiben in das Logfile? Könnte hilfreich sein für Validation-Warnings.

**Comment by claeis** [comment]
List der publizierten Behälter (Model, Topic, BID)

**Comment by ojeker** [comment]
Gemäss Besprechung angepasst. Basket ist optional, korrekt?

**Comment by claeis** [comment]
Nein,  auch BID ist zwingend (transient (bei erneutem Export anders) oder persistent (bei jedem Export identisch)).

**Comment by claeis** [comment]
Soll unter published wirklich der Timestamp (exakte Zeitpunkt) sein; wäre nicht das Datum (wie es für den Name des Verzeichnisses im  Filesystem) benutzt wird besser?

**Comment by claeis** [comment]
Das JSON funktioniert so nicht: es könnte ja sein, dass die einzelnen Datasets/Parts nicht die selben Baskets enthält (die BasketId ist sogar ziemlich sicher nicht identisch).

**Comment by claeis** [comment]
Vorschlag ohne Regionen:
```
{
	"dataIdent": "ch.so.afu.gewaesserschutz",
	"published": "2021-12-23T14:54:49.050062",
	"publishedBaskets": [{
		"model": "SO_AGI_MOpublic_20201009",
		"topic": "Bodenbedeckung",
		"basket": "oltenBID"
	}, {
		"model": "DM01",
		"topic": "Liegenschaften",
		"basket": "wangenBID"
	}]
}
```
Vorschlag mit Regionen:
```
{
	"dataIdent": "ch.so.afu.gewaesserschutz",
	"published": "2021-12-23T14:54:49.050062",
	"publishedRegions": [{
		"region": "olten",
		"publishedBaskets": [{
			"model": "SO_AGI_MOpublic_20201009",
			"topic": "Bodenbedeckung",
			"basket": "oltenBID"
		}]
	}, {
		"region": "wangen",
		"publishedBaskets": [{
			"model": "SO_AGI_MOpublic_20201009",
			"topic": "Bodenbedeckung",
			"basket": "wangenBID"
		}]
	}]
}
```

**Comment by ojeker** [comment]
Danke Claude
Du hast wahrscheinlich den Vorschlag mit Regionen, unter Beibehaltung von published als Timestamp (nicht Änderung auf Datum) umgesetzt....? Die anderen Vorschläge würden den Anforderungen widersprechen.

Bitte das Json des POST noch kurz Dokumentieren (Zutreffender Vorschlag von oben) - passt meiner Meinung nach ins Kapitel https://github.com/sogis/gretl/blob/master/docs/user/Publisher.md#kgdi-service

**Comment by claeis** [comment]
Der Client (gretl) dünkt mich der falsche Ort, aber ich habs ergänzt (Der richtige Ort, wäre m.E. der Service)

**Comment by ojeker** [comment]
Danke Claude.
Da Client-Post finde ich den Ort gut - verstehe auch, dass man das anders sehen kann.
