### ISSUE TITLE
region aus DB publizieren

### ISSUE THREAD

**Issue by barpasen** [sogis/gretl#82]
Ausgangslage: lokale DB mit Nutzungsplanung, 3 datatsets (siehe region1.png, region2.png)

Gretl-Job
task publishFromDb9(type: Publisher){
    dataIdent = "ch.so.arp.nutzungsplanung.publishFromDb9"
    database = [dbUriPub, dbUserPub, dbPwdPub]
    dbSchema = "arp_nutzungsplanung_pub_v1"
    modeldir = "http://models.geo.admin.ch/;http://geo.so.ch/models"
    target = [project.buildDir]
    
    //region = "[2][5][8][0]"
    //region = "[2][5][8][0]{1}"
    //region = "[0-9][0-9][0-9][0-9]"
    //region = "2580"
    //region = 2580
    //region = "[2]*"
    //region = "[9][8][0][9][7]"                      // bei allen Versuchen Fehlermeldung: "dataset OR region OR regions must be set"
}
![region1](https://user-images.githubusercontent.com/38491509/189667875-6c25c13d-c227-40ad-b8fb-a935d70d7990.png)
![region2](https://user-images.githubusercontent.com/38491509/189667913-7ad1e34c-1955-4fa1-9500-4d494fcacef0.png)

Publizieren von 4 Files (2581.xtf, 2582.xtf, 2583.xtf, 2584.xtf)
Export funktioniert mit den xtf-Files, inklusive Weitergabe "publishedRegions"

**Comment by claeis** [comment]
Parameter Pruefung war falsch

**Comment by barpasen** [comment]
Funktioniert nun einwandfrei
