### ISSUE TITLE
Archiv umfasst die Benutzerderivate

### ISSUE THREAD

**Issue by ojeker** [sogis/gretl#83]
In der ersten Version des Publisher werden auch die Benutzerderivate (gpkg, shp,...) in das Archiv übernommen. Es soll aber nur das Interlis-Transferfile archiviert werden.

Lösungs-Alternativen: 
* Sofortiges Abstreifen beim "Kopieren" nach /hist
* Abstreifen im Rahmen einer Archivausdünnung (Falls der Hist-Stand älter als z.B: 1 Monat ist)

**Comment by ojeker** [comment]
@edigonzales Was meinst du? Ich bin für sofortiges Abstreifen.

**Comment by edigonzales** [comment]
Falls ich es richtig verstanden habe, würden bei Variante 2 die XTF anders ausgedünnt resp. archiviert als die Benutzerderivate? Dann lieber Variante "sofort abstreifen".

**Comment by claeis** [comment]
Beim verschieben der aktuellen Version in die History, sollen die Benutzerderivate entfernt werden
