### ISSUE TITLE
Temporäres Verzeichnis nach Abbruch des Tasks löschen oder wieder überschreiben

### ISSUE THREAD

**Issue by barpasen** [sogis/gretl#84]
Bricht der Publisher-Task nach einem Fehler ab, bleibt im Verzeichnis dataIdent  (im Test in [project.buildDir]) das temporäre Verzeichnis .2022-09-13 stehen.
Bei einer erneuten Ausführung des Tasks kommt die Fehlermeldung:
java.nio.file.FileAlreadyExistsException: /home/gradle/project/build/ch.so.arp.nutzungsplanung.publishFromDb8/.2022-09-13/meta/CoordSys-20151124.ili

**Comment by claeis** [comment]
ja, temp sollte am Ende bei einem Fehler entfernt werden (bei einem neuen Durchlauf, sollte es einen Fehler geben; ist evtl eine Folge eines Konfig-Fehlers)

**Comment by barpasen** [comment]
Nun wird das temporäre Verzeichnis gelöscht nach einem Fehler
