### ISSUE TITLE
modeldir definieren wenn userFormats = true gesetzt ist

### ISSUE THREAD

**Issue by barpasen** [sogis/gretl#85]
wenn userFormats = true gesetzt ist, muss modeldir angegeben werden, sonst wird das Modell nicht gefunden. Wird userFormats nicht gesetzt, muss modeldir nicht angegeben werden. Gibt es einen Grund für das unterschiedliche Verhalten?

task publishFromDb3(type: Publisher) {
    dataIdent = "ch.so.arp.nutzungsplanung.publishFromDb3"
    database = [dbUriPub, dbUserPub, dbPwdPub]
    dbSchema = "arp_nutzungsplanung_pub_v1"
    target = [project.buildDir]
    //modeldir = "http://models.geo.admin.ch/;http://geo.so.ch/models"
    //userFormats = true
    dataset = "2580"
    kgdiService = ["http://localhost:8080/app/rest","usr","pwd"]
}

**Comment by claeis** [comment]
userFormats = true sollte kein Unterschied machen

**Comment by barpasen** [comment]
task publishFromDb12(type: Publisher) {
    database = [dbUriPub, dbUserPub, dbPwdPub]
    dataIdent = "ch.so.awjf_wildtierkorridore.publishFromDb12"
    dbSchema = "awjf_wildtierkorridore"
    target = [project.buildDir]
    // modeldir = "https://models.geo.admin.ch/;https://geo.so.ch/models"
    modelsToPublish = "SO_AWJF_Wildtierkorridore_20210831"
    userFormats = true
    kgdiService = ["http://localhost:8080/app/rest","admin","admin"]
}

Execution failed for task ':publishFromDb12'.
> Inner Exception Message: no modeldir given

Ohne "userFormats = true" und ohne "modeldir" wird der Task fehlerfrei ausgeführt.
Das Modell ist im Repo https://geo.so.ch/models, müsste also über das default-modeldir gefunden werden.

**Comment by barpasen** [comment]
@claeis Hoi Claude, konntest du das in der Zwischenzeit mal anschauen?

**Comment by barpasen** [comment]
Funktioniert nun bei userFormats = true ohne Angabe von modeldir
