### ISSUE TITLE
Publikation ohne Dataset

### ISSUE THREAD

**Issue by ojeker** [sogis/gretl#89]
Abhängig von der Modell-Komplexität verlangt ili2pg das Anlegen einer Basket-Column.

Dei Publisher-API verlangt in diesen Fällen die Angabe eines dataset oder einer Regex auf den Dataset-Namen [region].

Wir können nun nicht künstlich ein Dataset anlegen, "nur" weil eine Basket-Referenz vorhanden ist.

Wie kann das gelöst werden? Analogie zu ili2pg --exportModels?

**Comment by claeis** [comment]
Was ist der Unterschied zum bereits gemachten modelsToPublish in #78?

**Comment by claeis** [comment]
```
task publishFromDb(type: Publisher){
  dataIdent = "ch.so.agi.vermessung"
  target = [ "sftp://ftp.server.ch/data", "user", "password" ]
  database = ["uri","user","password"]
  dbSchema "av"
  modelsToPublish = "ExtendedModel"
  exportModels = "BaseModel"
}
```

**Comment by claeis** [comment]
bleibt wie es ist gem. E-Mail 2022-11-21
