### ISSUE TITLE
Authentication von /doc

### ISSUE THREAD

**Issue by ojeker** [sogis/gretl#90]
Die Authentifizierung von [kgdiService]/doc funktioniert noch nicht.  [kgdiService]/pubsignal funktioniert.

Zu beachten: Der erneute Request für ein Token kommt im Backend rest/v2/oauth/token an, der darauf folgende Aufruf auf [kgdiService]/doc schlägt jedoch fehl.

Mit diesem CURL-Befehl funktioniert es:

    curl -X GET \
    -H 'Authorization: Bearer _access_token_' \
    -H "Content-Type: text/html" \
    'http://localhost:8080/app/rest/doc?dataident=inttest.publishsrv.NoRegion_NoSuffix_NoPsubs.suffix'     

`_access_token_ ersetzen mit dem eigentlichen Token...`

**Comment by claeis** [comment]
Der Aufruf des Publisher umfasst noch den Parameter published. Ist das evtl. das Problem oder liegt es am fehlenden Content-Type?

    HTTP GET: endpoint+"/doc?dataident="+dataIdent+"&published="+versionTag

**Comment by ojeker** [comment]
Da man nie ganz sicher sein kann habe ich das ausprobiert - leider Fehlanzeige - das folgende curl funktioniert.

    curl -X GET \
    -H 'Authorization: Bearer V8APi8OyoBiCerMX18qD8W9lFwc' \
    'http://localhost:8080/app/rest/doc?published=2021-12-23T14:50:59.825849&dataident=inttest.publishsrv.NoRegion_NoSuffix_NoPsubs.suffix'

Der Endpoint /doc lehnt den Request weiterhin mit einem 401-Fehler ab:
 
    Unauthorized: An Authentication object was not found in the SecurityContext

Auszug aus log von GRETL/Publisher:

    [...] POST /app/rest/v2/oauth/token [...]
    [...]
    [...] GET /app/rest/doc?dataident=ch.so.afu.fliessgewaesser&published=2022-11-08T11:25:17.477 [...]
    11:25:43.252 [DEBUG] [sun.net.www.protocol.http.HttpURLConnection] sun.net.www.MessageHeader@36c0507a14 pairs: {null: HTTP/1.1 401 Unauthorized}{Date: Tue, 08 Nov 2022 11:25:43 GMT}{Vary: Origin}{Vary: Access-Control-Request-Method}{Vary: Access-Control-Request-Headers}{Cache-Control: no-store}{Pragma: no-cache}{WWW-Authenticate: Bearer realm="rest-api", error="unauthorized", error_description="An Authentication object was not found in the SecurityContext"}{Content-Type: application/xml;charset=UTF-8}{X-XSS-Protection: 1; mode=block}{X-Frame-Options: DENY}{X-Content-Type-Options: nosniff}{Transfer-Encoding: chunked}{Server: Jetty(9.4.32.v20200930)}
    11:25:43.254 [INFO] [ch.so.agi.gretl.util.SimiSvcClient] <UnauthorizedException><error>unauthorized</error><error_description>An Authentication object was not found in the SecurityContext</error_description></UnauthorizedException>

**Comment by ojeker** [comment]
Vorschläge, wie wir dem Problem schnell auf die Schliche kommen sind willkommen :)

**Comment by edigonzales** [comment]
Ich kenn die Vorgeschichte nicht, darum Schüsse ins Blaue:

- Gewollt OAuth und nicht Basic Auth?
- Fehlermeldung kommt von Spring Boot resp Spring Security -> Dort grübeln. 
- Notfalls Cuba irgendwie umgehen.

**Comment by claeis** [comment]
Im Server-Code+Log schauen, warum es der Server zurückweist.

**Comment by claeis** [comment]
Mal den Beipackzettel weglassen

**Comment by edigonzales** [comment]
Content-Type korrekt/explizit mitschicken?

Welcher wird erwartet? Json? x-www-form-urlencoded? ....?

**Comment by edigonzales** [comment]
logging.level.org.springframework.security=DEBUG (oder grüsel-yaml-äquivalent).

Oder ohne security, dann wird alles von Spring im debug level geloggt. Notfalls TRACE.

**Comment by ojeker** [comment]
Danke für die Inputs

Ich habe die loglevel für Framework und SIMI angehoben und mir die Header ausgeben lassen.

Bei Aufruf mittels CURL (lokal)

    2022-11-10 13:08:24.927 INFO  [http-nio-8080-exec-17/app-core/server] com.haulmont.cuba.security.auth.AuthenticationManagerBean - Logged in: bec8bb17-4baa-6430-3a69-f46b8d5d2066 [notifier]
    2022-11-10 13:08:24.973 INFO  [http-nio-8080-exec-17/app/notifier] com.haulmont.addon.restapi.api.auth.ClientProxyTokenStore - REST API access token stored: [notifier] ***Gnxc
    2022-11-10 13:11:57.594 DEBUG [http-nio-8080-exec-3] ch.so.agi.simi.web.api.themepub.DataDocController - Dataident = inttest.publishsrv.NoRegion_NoSuffix_NoPsubs.suffix
    2022-11-10 13:11:57.595 DEBUG [http-nio-8080-exec-3] ch.so.agi.simi.web.api.themepub.DataDocController - Header 'host' = localhost:8080
    2022-11-10 13:11:57.595 DEBUG [http-nio-8080-exec-3] ch.so.agi.simi.web.api.themepub.DataDocController - Header 'user-agent' = curl/7.68.0
    2022-11-10 13:11:57.595 DEBUG [http-nio-8080-exec-3] ch.so.agi.simi.web.api.themepub.DataDocController - Header 'accept' = */*
    2022-11-10 13:11:57.595 DEBUG [http-nio-8080-exec-3] ch.so.agi.simi.web.api.themepub.DataDocController - Header 'authorization' = Bearer ***Gnxc
    2022-11-10 13:11:57.595 DEBUG [http-nio-8080-exec-3] ch.so.agi.simi.web.api.themepub.DataDocController - Header 'content-type' = text/html

Bei Aufruf aus GRETL-Publisher (deployt)

    2022-11-10 16:52:06.550 INFO [qtp1209669119-17/app-core/server] com.haulmont.cuba.security.auth.AuthenticationManagerBean - Logged in: 3c466966-fec8-6631-077b-f19c980292a8 [gretl]
    2022-11-10 16:52:06.564 INFO [qtp1209669119-17/app/gretl] com.haulmont.addon.restapi.api.auth.ClientProxyTokenStore - REST API access token stored: [gretl] ***uhMI
    2022-11-10 16:52:06.571 DEBUG [qtp1209669119-14] ch.so.agi.simi.web.api.themepub.DataDocController - Dataident = ch.so.afu.fliessgewaesser
    2022-11-10 16:52:06.571 DEBUG [qtp1209669119-14] ch.so.agi.simi.web.api.themepub.DataDocController - Header 'Accept' = text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2
    2022-11-10 16:52:06.571 DEBUG [qtp1209669119-14] ch.so.agi.simi.web.api.themepub.DataDocController - Header 'User-Agent' = Java/1.8.0_333
    2022-11-10 16:52:06.571 DEBUG [qtp1209669119-14] ch.so.agi.simi.web.api.themepub.DataDocController - Header 'Connection' = keep-alive
    2022-11-10 16:52:06.571 DEBUG [qtp1209669119-14] ch.so.agi.simi.web.api.themepub.DataDocController - Header 'Host' = simi.gdi-integration.svc

Der Header mit dem Auth-Token kommt nicht beim deployten SIMI an. Das passt zu der Fehlermeldung.   
Fehlender Header:

    'authorization' = Bearer ***Gnxc

**Comment by edigonzales** [comment]
Ah, Client lokal (also curl) funktioniert es? Dann "frisst" jemand dazwischen was weg. Welche Wege nehmen die Requests vom deployten GRETL zum SIMI? SES? Oder nur Openshift intern? SES ist im Regelfall brutal streng, der lässt praktisch nix durch ohne Spezialkonfiguration.

cc @schmandr

**Comment by schmandr** [comment]
Der Request wird OpenShift-intern gemacht, auf http://simi.gdi-integration.svc/app/rest. Also nicht über den SES.

```
java.io.IOException: failed to send get doc request to service at http://simi.gdi-integration.svc/app/rest
	at ch.so.agi.gretl.util.SimiSvcClient.getLeaflet(SimiSvcClient.java:79)
	at ch.so.agi.gretl.steps.PublisherStep.publishFilePost(PublisherStep.java:589)
	at ch.so.agi.gretl.steps.PublisherStep.publishDatasetFromDb(PublisherStep.java:233)
	at ch.so.agi.gretl.tasks.Publisher.publishAll(Publisher.java:200)
```

**Comment by edigonzales** [comment]
Ah moment, könnte es dann auch sein, dass GRETL was gar nicht mitschickt? Oder haben wir das bereits ausgeschlossen?

**Comment by schmandr** [comment]
> Ah moment, könnte es dann auch sein, dass GRETL was gar nicht mitschickt? Oder haben wir das bereits ausgeschlossen?

Ja, könnte gut sein. Denn der obige Vergleich ist ja zwischen curl (lokal) und GRETL (Betrieb). Also auf jeden Fall hilfreich, aber irgendwie auch noch im Bereich Äpfel - Birnen ;-)

**Comment by edigonzales** [comment]
https://github.com/sogis/gretl/blob/master/gretl/src/main/java/ch/so/agi/gretl/util/SimiSvcClient.java Eventuell hier loggen was wirklich genau rausgeht.

@schmandr Kann man in Openshift irgendwo den Request debuggen, wenn es nicht übers API-Gateway geht?

**Comment by edigonzales** [comment]
Und hat man GRETL lokal ausprobiert?

**Comment by claeis** [comment]
Da filtert irgenwer/irgendwas. Weil rein von der Code-Logik kommt Content-Type immer (fehlt ja aber offenbar auch). Und Authorization kommt auch immer (ausser der token Bezug schlägt fehl; aber dann findet der /doc Aufruf auch gar nicht statt).

**Comment by schmandr** [comment]
> @schmandr Kann man in Openshift irgendwo den Request debuggen, wenn es nicht übers API-Gateway geht?

Nur entweder auf Seite GRETL oder auf Seite Simi. Letzteres wäre das Beste, aber soviel ich weiss ist im Moment eine "Workaround-Version" in Betrieb, einfach damit das Ganze überhaupt einmal durchläuft.

> Und hat man GRETL lokal ausprobiert?

Weiss ich nicht.

**Comment by claeis** [comment]
dieses Log muss ich dann wieder ausbauen...

**Comment by edigonzales** [comment]
Kann man eventuell noch low level loggen? 

Beim neuen HttpClient z.B. so -Djdk.httpclient.HttpClient.log=requests,headers,frames:all,content,ssl,trace,channel,all

**Comment by edigonzales** [comment]
Eventuell `System.setProperty("javax.net.debug","all");`

**Comment by schmandr** [comment]
Ich konnte die Sache nun lokal ausführen. Folgendes Log stammt von GRETL Tag 2.2.286.
Da scheint mir nun doch, dass GRETL beim `rest/v2/oauth/token`-Request zwar `Content-Type` und `Authorization` mitschickt, beim `rest/doc`-Request aber nicht mehr. (Frage ist aber: Muss es denn das? Oder ist hierfür denn nicht das Token da? Da komm' ich nicht draus.)

```
11:11:50.163 [INFO] [ch.so.agi.gretl.util.SimiSvcClient] authHeaderValue <Basic cmVzdGlkOnJlc3RwYXNz>
11:11:50.165 [DEBUG] [sun.net.www.protocol.http.HttpURLConnection] sun.net.www.MessageHeader@15ebb7248 pairs: {POST /app/rest/v2/oauth/token HTTP/1.1: null}{Content-Type: application/x-www-form-urlencoded}{Authorization: Basic cmVzdGlkOnJlc3RwYXNz}{User-Agent: Java/1.8.0_333}{Host: simi.apps.ocp.so.ch}{Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2}{Connection: keep-alive}{Content-Length: 64}
11:11:50.270 [DEBUG] [sun.net.www.protocol.http.HttpURLConnection] sun.net.www.MessageHeader@1315d4a414 pairs: {null: HTTP/1.1 200 OK}{date: Fri, 11 Nov 2022 11:11:50 GMT}{vary: Origin}{vary: Access-Control-Request-Method}{vary: Access-C
ontrol-Request-Headers}{cache-control: no-store}{pragma: no-cache}{content-type: application/json;charset=utf-8}{x-xss-protection: 1; mode=block}{x-frame-options: DENY}{x-content-type-options: nosniff}{transfer-encoding: chunked}{server:
 Jetty(9.4.32.v20200930)}{set-cookie: b163f56d6a39d75fe4d30ddc51f5547a=be17254bfc04694cf83e65eb75d068d9; path=/; HttpOnly}
11:11:50.271 [INFO] [ch.so.agi.gretl.util.SimiSvcClient] {"access_token":"ZLruK8VSRcgI3fPn1XxC-BDzcg0","token_type":"bearer","refresh_token":"ZiqsuLgxuRq8dD-XNqlqC-Aj8HQ","expires_in":43199,"scope":"rest-api"}
11:11:50.280 [INFO] [ch.so.agi.gretl.util.SimiSvcClient] accessToken <ZLruK8VSRcgI3fPn1XxC-BDzcg0>
11:11:50.281 [DEBUG] [sun.net.www.protocol.http.HttpURLConnection] sun.net.www.MessageHeader@54e2103c5 pairs: {GET /app/rest/doc?dataident=ch.so.afu.fliessgewaesser&published=2022-11-11T11:11:37.436 HTTP/1.1: null}{User-Agent: Java/1.8.0
_333}{Host: simi.apps.ocp.so.ch}{Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2}{Connection: keep-alive}
11:11:50.334 [DEBUG] [sun.net.www.protocol.http.HttpURLConnection] sun.net.www.MessageHeader@696f4ef015 pairs: {null: HTTP/1.1 401 Unauthorized}{date: Fri, 11 Nov 2022 11:11:50 GMT}{vary: Origin}{vary: Access-Control-Request-Method}{vary
: Access-Control-Request-Headers}{cache-control: no-store}{pragma: no-cache}{www-authenticate: Bearer realm="rest-api", error="unauthorized", error_description="An Authentication object was not found in the SecurityContext"}{content-type
: application/xml;charset=UTF-8}{x-xss-protection: 1; mode=block}{x-frame-options: DENY}{x-content-type-options: nosniff}{transfer-encoding: chunked}{server: Jetty(9.4.32.v20200930)}{set-cookie: b163f56d6a39d75fe4d30ddc51f5547a=be17254bf
c04694cf83e65eb75d068d9; path=/; HttpOnly}
11:11:50.338 [INFO] [ch.so.agi.gretl.util.SimiSvcClient] <UnauthorizedException><error>unauthorized</error><error_description>An Authentication object was not found in the SecurityContext</error_description></UnauthorizedException>
```

In Simi (Tag 2.2.173, das ist derjenige noch ohne Workaround) wird brutal viel geloggt. Man sieht hier, dass beim `rest/doc`-Request `Content-Type` und `Authorization` nicht ankommen.

```
2022-11-11 11:11:50.170 DEBUG [qtp1209669119-18] org.eclipse.jetty.server.HttpChannel - REQUEST for //simi.apps.ocp.so.ch/app/rest/v2/oauth/token on HttpChannelOverHttp@14938584{s=HttpChannelState@6590ce5e{s=IDLE rs=BLOCKING os=OPEN is=IDLE awp=false se=false i=true al=0},r=1,c=false/false,a=IDLE,uri=//simi.apps.ocp.so.ch/app/rest/v2/oauth/token,age=0}
POST //simi.apps.ocp.so.ch/app/rest/v2/oauth/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: Basic cmVzdGlkOnJlc3RwYXNz
User-Agent: Java/1.8.0_333
Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2
Content-Length: 64
Host: simi.apps.ocp.so.ch
X-Forwarded-Host: simi.apps.ocp.so.ch
X-Forwarded-Port: 80
X-Forwarded-Proto: http
Forwarded: for=10.36.43.202;host=simi.apps.ocp.so.ch;proto=http
X-Forwarded-For: 10.36.43.202

[...]

2022-11-11 11:11:50.331 DEBUG [qtp1209669119-16] org.eclipse.jetty.server.HttpChannel - REQUEST for //simi.apps.ocp.so.ch/app/rest/doc?dataident=ch.so.afu.fliessgewaesser&published=2022-11-11T11:11:37.436 on HttpChannelOverHttp@14938584{s=HttpChannelState@6590ce5e{s=IDLE rs=BLOCKING os=OPEN is=IDLE awp=false se=false i=true al=0},r=2,c=false/false,a=IDLE,uri=//simi.apps.ocp.so.ch/app/rest/doc?dataident=ch.so.afu.fliessgewaesser&published=2022-11-11T11:11:37.436,age=0}
GET //simi.apps.ocp.so.ch/app/rest/doc?dataident=ch.so.afu.fliessgewaesser&published=2022-11-11T11:11:37.436 HTTP/1.1
User-Agent: Java/1.8.0_333
Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2
Host: simi.apps.ocp.so.ch
X-Forwarded-Host: simi.apps.ocp.so.ch
X-Forwarded-Port: 80
X-Forwarded-Proto: http
Forwarded: for=10.36.43.202;host=simi.apps.ocp.so.ch;proto=http
X-Forwarded-For: 10.36.43.202
[...]
2022-11-11 11:11:50.332 DEBUG [qtp1209669119-16] org.springframework.security.web.access.ExceptionTranslationFilter - Authentication exception occurred; redirecting to authentication entry point
org.springframework.security.authentication.AuthenticationCredentialsNotFoundException: An Authentication object was not found in the SecurityContext
```

**Comment by edigonzales** [comment]
https://github.com/sogis/gretl/blob/60f42f8ff66053104cfd605d5accde7c1089fa48/gretl/src/main/java/ch/so/agi/gretl/util/SimiSvcClient.java#L102 ff

Im GRETL-Log sehe ich `authHeaderValue ` nur einmal, beim POST-Request. Beim GET-Request `/doc` müsste das doch jetzt auch erscheinen, wenn ich die Methode `doHttpRequest` anschaue: https://github.com/sogis/gretl/blob/60f42f8ff66053104cfd605d5accde7c1089fa48/gretl/src/main/java/ch/so/agi/gretl/util/SimiSvcClient.java#L144 

Es wird geloggt, falls ungleich null und ebenso wird dann das Authorization Property gesetzt: `conn.setRequestProperty("Authorization", authHeaderValue);` Was es nicht macht (?)

**Comment by edigonzales** [comment]
cc @claeis @ojeker 

@schmandr und ich denken, haben den Bug gefunden:

https://github.com/sogis/gretl/blob/60f42f8ff66053104cfd605d5accde7c1089fa48/gretl/src/main/java/ch/so/agi/gretl/util/SimiSvcClient.java#L76

Methodenparameter request ist null. Dann siehe Zeile 141. Content-Type und Auth Header wird nur gesetzt, falls request != null:

https://github.com/sogis/gretl/blob/60f42f8ff66053104cfd605d5accde7c1089fa48/gretl/src/main/java/ch/so/agi/gretl/util/SimiSvcClient.java#L141
