### ISSUE TITLE
Schlüsselpaare für die Authentifizierung (restid / retpass)

### ISSUE THREAD

**Issue by ojeker** [sogis/gretl#91]
Im Moment sind URL/Benutzer/Passwort hardcodiert.

Diese bitte analog "kgdiService" konfigurierbar machen. (Neuer Publisher-Parameter kgdiTokenService)

**Comment by claeis** [comment]
also url, usr, pwd oder nur usr, pwd?

**Comment by ojeker** [comment]
url, usr, pwd
