### ISSUE TITLE
Falsch konfiguriertes grooming wird still ignoriert

### ISSUE THREAD

**Issue by ojeker** [sogis/gretl#96]
task publishPub(type: Publisher){//, dependsOn: writeToPub){
        grooming = "nonExisting.json"
    }

Obwohl die referenzierte Datei gar nicht existiert, läuft der Publisher ohne Fehler durch.

**Comment by claeis** [comment]
Was ist genau das Ziel:

  A) Falscher Dateiname ist zwar zulässig aber ungewöhnlich, und soll darum rapportiert werden
  B) Falscher Dateiname soll zu einem Fehler des Publishers führen
