### ISSUE TITLE
Erzeugung dxf geobau

### ISSUE THREAD

**Issue by ojeker** [sogis/gretl#99]
Dieser Spezialfall passt noch nicht. Im Gegensatz zum generischen dxf muss das geobau dxf auch ab Quelle "Transferfile" und nicht nur ab Quelle "Datenbank" generiert werden können.

Fragen dazu:
* Braucht es überhaupt die Einschränkung, dass userFormats nur mit Quelle "Datenbank" erzeugt werden können? Leiten sich diese nicht immer via "Ili-Geopackage" vom TransferFile ab? Bei Quelle Datenbank wird einfach als Erstes das Transferfile aus der DB exportiert?
* Für das Modell DM01AVCH24LV95D möchten neben dem itf nur das dxf geobau publizieren. Wie am Besten konfigurieren? Neue Boolean-Property "geobauDxf", mit Fehlermeldung, falls Modell nicht gleich DM01AVCH24LV95D?

Zur Info anbei Konfig-Beispiel... 

    task publish(type: Publisher)
        dataIdent = 'ch.so.agi.av.dm01_ch'
        modelsToPublish = 'DM01AVCH24LV95D'
        userFormats = true
        sourcePath = new File(dm01ChDir, '2421.itf')
        target = [file("$buildDir/published")]
    }
 
und Fehlermeldung

    * What went wrong:
    Execution failed for task ':1_dm01_ch:publish'.
    > userFormats requires a database as source

**Comment by claeis** [comment]
DM01 ist sowieso ja speziell. Braucht es überhaupt den zusätzlichen "geobauDxf "Parameter?

**Comment by ojeker** [comment]
Gute Frage, die ich mir auch gestellt habe. Aus Transparenzgründen habe ich das so vorgeschlagen. Bin offen für anderen Vorschlag...
